// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the GNU Affero
// General Public License v3.0 or later. See the LICENSE file in the
// project root.
//
// GENERATED by tool/generate_carbon_themes.py — do not edit by hand.

import 'dart:ui';

import 'package:carbide/carbide.dart';
import 'package:flutter_test/flutter_test.dart';

Color _alpha(Color color, double opacity) => color.withValues(alpha: opacity);

void main() {
  test('white theme tokens match the Carbon source', () {
    expect(CarbonThemeData.white.brightness, Brightness.light);
    expect(CarbonThemeData.white.background, CarbonColors.white);
    expect(CarbonThemeData.white.backgroundInverse, CarbonColors.gray80);
    expect(CarbonThemeData.white.backgroundBrand, CarbonColors.blue60);
    expect(
      CarbonThemeData.white.backgroundActive,
      _alpha(CarbonColors.gray50, 0.5),
    );
    expect(
      CarbonThemeData.white.backgroundHover,
      _alpha(CarbonColors.gray50, 0.12),
    );
    expect(
      CarbonThemeData.white.backgroundInverseHover,
      CarbonColors.gray80Hover,
    );
    expect(
      CarbonThemeData.white.backgroundSelected,
      _alpha(CarbonColors.gray50, 0.2),
    );
    expect(
      CarbonThemeData.white.backgroundSelectedHover,
      _alpha(CarbonColors.gray50, 0.32),
    );
    expect(CarbonThemeData.white.layer01, CarbonColors.gray10);
    expect(CarbonThemeData.white.layerActive01, CarbonColors.gray30);
    expect(CarbonThemeData.white.layerBackground01, CarbonColors.white);
    expect(CarbonThemeData.white.layerHover01, CarbonColors.gray10Hover);
    expect(CarbonThemeData.white.layerSelected01, CarbonColors.gray20);
    expect(
      CarbonThemeData.white.layerSelectedHover01,
      CarbonColors.gray20Hover,
    );
    expect(CarbonThemeData.white.layer02, CarbonColors.white);
    expect(CarbonThemeData.white.layerActive02, CarbonColors.gray30);
    expect(CarbonThemeData.white.layerBackground02, CarbonColors.gray10);
    expect(CarbonThemeData.white.layerHover02, CarbonColors.whiteHover);
    expect(CarbonThemeData.white.layerSelected02, CarbonColors.gray20);
    expect(
      CarbonThemeData.white.layerSelectedHover02,
      CarbonColors.gray20Hover,
    );
    expect(CarbonThemeData.white.layer03, CarbonColors.gray10);
    expect(CarbonThemeData.white.layerActive03, CarbonColors.gray30);
    expect(CarbonThemeData.white.layerBackground03, CarbonColors.white);
    expect(CarbonThemeData.white.layerHover03, CarbonColors.gray10Hover);
    expect(CarbonThemeData.white.layerSelected03, CarbonColors.gray20);
    expect(
      CarbonThemeData.white.layerSelectedHover03,
      CarbonColors.gray20Hover,
    );
    expect(CarbonThemeData.white.layerSelectedInverse, CarbonColors.gray100);
    expect(CarbonThemeData.white.layerSelectedDisabled, CarbonColors.gray50);
    expect(CarbonThemeData.white.layerAccent01, CarbonColors.gray20);
    expect(CarbonThemeData.white.layerAccentActive01, CarbonColors.gray40);
    expect(CarbonThemeData.white.layerAccentHover01, CarbonColors.gray20Hover);
    expect(CarbonThemeData.white.layerAccent02, CarbonColors.gray20);
    expect(CarbonThemeData.white.layerAccentActive02, CarbonColors.gray40);
    expect(CarbonThemeData.white.layerAccentHover02, CarbonColors.gray20Hover);
    expect(CarbonThemeData.white.layerAccent03, CarbonColors.gray20);
    expect(CarbonThemeData.white.layerAccentActive03, CarbonColors.gray40);
    expect(CarbonThemeData.white.layerAccentHover03, CarbonColors.gray20Hover);
    expect(CarbonThemeData.white.field01, CarbonColors.gray10);
    expect(CarbonThemeData.white.fieldHover01, CarbonColors.gray10Hover);
    expect(CarbonThemeData.white.field02, CarbonColors.white);
    expect(CarbonThemeData.white.fieldHover02, CarbonColors.whiteHover);
    expect(CarbonThemeData.white.field03, CarbonColors.gray10);
    expect(CarbonThemeData.white.fieldHover03, CarbonColors.gray10Hover);
    expect(CarbonThemeData.white.borderSubtle00, CarbonColors.gray20);
    expect(CarbonThemeData.white.borderSubtle01, CarbonColors.gray30);
    expect(CarbonThemeData.white.borderSubtleSelected01, CarbonColors.gray30);
    expect(CarbonThemeData.white.borderSubtle02, CarbonColors.gray20);
    expect(CarbonThemeData.white.borderSubtleSelected02, CarbonColors.gray30);
    expect(CarbonThemeData.white.borderSubtle03, CarbonColors.gray30);
    expect(CarbonThemeData.white.borderSubtleSelected03, CarbonColors.gray30);
    expect(CarbonThemeData.white.borderStrong01, CarbonColors.gray50);
    expect(CarbonThemeData.white.borderStrong02, CarbonColors.gray50);
    expect(CarbonThemeData.white.borderStrong03, CarbonColors.gray50);
    expect(CarbonThemeData.white.borderTile01, CarbonColors.gray30);
    expect(CarbonThemeData.white.borderTile02, CarbonColors.gray40);
    expect(CarbonThemeData.white.borderTile03, CarbonColors.gray30);
    expect(CarbonThemeData.white.borderInverse, CarbonColors.gray100);
    expect(CarbonThemeData.white.borderInteractive, CarbonColors.blue60);
    expect(CarbonThemeData.white.borderDisabled, CarbonColors.gray30);
    expect(CarbonThemeData.white.textPrimary, CarbonColors.gray100);
    expect(CarbonThemeData.white.textSecondary, CarbonColors.gray70);
    expect(
      CarbonThemeData.white.textPlaceholder,
      _alpha(CarbonColors.gray100, 0.4),
    );
    expect(CarbonThemeData.white.textHelper, CarbonColors.gray60);
    expect(CarbonThemeData.white.textError, CarbonColors.red60);
    expect(CarbonThemeData.white.textInverse, CarbonColors.white);
    expect(CarbonThemeData.white.textOnColor, CarbonColors.white);
    expect(CarbonThemeData.white.textOnColorDisabled, CarbonColors.gray50);
    expect(
      CarbonThemeData.white.textDisabled,
      _alpha(CarbonColors.gray100, 0.25),
    );
    expect(CarbonThemeData.white.linkPrimary, CarbonColors.blue60);
    expect(CarbonThemeData.white.linkPrimaryHover, CarbonColors.blue70);
    expect(CarbonThemeData.white.linkSecondary, CarbonColors.blue70);
    expect(CarbonThemeData.white.linkInverse, CarbonColors.blue40);
    expect(CarbonThemeData.white.linkVisited, CarbonColors.purple60);
    expect(CarbonThemeData.white.linkInverseVisited, CarbonColors.purple40);
    expect(CarbonThemeData.white.linkInverseActive, CarbonColors.gray10);
    expect(CarbonThemeData.white.linkInverseHover, CarbonColors.blue30);
    expect(CarbonThemeData.white.iconPrimary, CarbonColors.gray100);
    expect(CarbonThemeData.white.iconSecondary, CarbonColors.gray70);
    expect(CarbonThemeData.white.iconInverse, CarbonColors.white);
    expect(CarbonThemeData.white.iconOnColor, CarbonColors.white);
    expect(CarbonThemeData.white.iconOnColorDisabled, CarbonColors.gray50);
    expect(
      CarbonThemeData.white.iconDisabled,
      _alpha(CarbonColors.gray100, 0.25),
    );
    expect(CarbonThemeData.white.iconInteractive, CarbonColors.blue60);
    expect(CarbonThemeData.white.supportError, CarbonColors.red60);
    expect(CarbonThemeData.white.supportSuccess, CarbonColors.green50);
    expect(CarbonThemeData.white.supportWarning, CarbonColors.yellow30);
    expect(CarbonThemeData.white.supportInfo, CarbonColors.blue70);
    expect(CarbonThemeData.white.supportErrorInverse, CarbonColors.red50);
    expect(CarbonThemeData.white.supportSuccessInverse, CarbonColors.green40);
    expect(CarbonThemeData.white.supportWarningInverse, CarbonColors.yellow30);
    expect(CarbonThemeData.white.supportInfoInverse, CarbonColors.blue50);
    expect(CarbonThemeData.white.supportCautionMinor, CarbonColors.yellow30);
    expect(CarbonThemeData.white.supportCautionMajor, CarbonColors.orange40);
    expect(
      CarbonThemeData.white.supportCautionUndefined,
      CarbonColors.purple60,
    );
    expect(CarbonThemeData.white.focus, CarbonColors.blue60);
    expect(CarbonThemeData.white.focusInset, CarbonColors.white);
    expect(CarbonThemeData.white.focusInverse, CarbonColors.white);
    expect(CarbonThemeData.white.skeletonBackground, CarbonColors.whiteHover);
    expect(CarbonThemeData.white.skeletonElement, CarbonColors.gray30);
    expect(CarbonThemeData.white.interactive, CarbonColors.blue60);
    expect(CarbonThemeData.white.highlight, CarbonColors.blue20);
    expect(CarbonThemeData.white.overlay, _alpha(CarbonColors.black, 0.6));
    expect(CarbonThemeData.white.toggleOff, CarbonColors.gray50);
    expect(CarbonThemeData.white.shadow, const Color.fromRGBO(0, 0, 0, 0.3));
  });

  test('gray10 theme tokens match the Carbon source', () {
    expect(CarbonThemeData.gray10.brightness, Brightness.light);
    expect(CarbonThemeData.gray10.background, CarbonColors.gray10);
    expect(CarbonThemeData.gray10.backgroundInverse, CarbonColors.gray80);
    expect(CarbonThemeData.gray10.backgroundBrand, CarbonColors.blue60);
    expect(
      CarbonThemeData.gray10.backgroundActive,
      _alpha(CarbonColors.gray50, 0.5),
    );
    expect(
      CarbonThemeData.gray10.backgroundHover,
      _alpha(CarbonColors.gray50, 0.12),
    );
    expect(
      CarbonThemeData.gray10.backgroundInverseHover,
      CarbonColors.gray80Hover,
    );
    expect(
      CarbonThemeData.gray10.backgroundSelected,
      _alpha(CarbonColors.gray50, 0.2),
    );
    expect(
      CarbonThemeData.gray10.backgroundSelectedHover,
      _alpha(CarbonColors.gray50, 0.32),
    );
    expect(CarbonThemeData.gray10.layer01, CarbonColors.white);
    expect(CarbonThemeData.gray10.layerActive01, CarbonColors.gray30);
    expect(CarbonThemeData.gray10.layerBackground01, CarbonColors.gray10);
    expect(CarbonThemeData.gray10.layerHover01, CarbonColors.whiteHover);
    expect(CarbonThemeData.gray10.layerSelected01, CarbonColors.gray20);
    expect(
      CarbonThemeData.gray10.layerSelectedHover01,
      CarbonColors.gray20Hover,
    );
    expect(CarbonThemeData.gray10.layer02, CarbonColors.gray10);
    expect(CarbonThemeData.gray10.layerActive02, CarbonColors.gray30);
    expect(CarbonThemeData.gray10.layerBackground02, CarbonColors.white);
    expect(CarbonThemeData.gray10.layerHover02, CarbonColors.gray10Hover);
    expect(CarbonThemeData.gray10.layerSelected02, CarbonColors.gray20);
    expect(
      CarbonThemeData.gray10.layerSelectedHover02,
      CarbonColors.gray20Hover,
    );
    expect(CarbonThemeData.gray10.layer03, CarbonColors.white);
    expect(CarbonThemeData.gray10.layerActive03, CarbonColors.gray30);
    expect(CarbonThemeData.gray10.layerBackground03, CarbonColors.gray10);
    expect(CarbonThemeData.gray10.layerHover03, CarbonColors.whiteHover);
    expect(CarbonThemeData.gray10.layerSelected03, CarbonColors.gray20);
    expect(
      CarbonThemeData.gray10.layerSelectedHover03,
      CarbonColors.gray20Hover,
    );
    expect(CarbonThemeData.gray10.layerSelectedInverse, CarbonColors.gray100);
    expect(CarbonThemeData.gray10.layerSelectedDisabled, CarbonColors.gray50);
    expect(CarbonThemeData.gray10.layerAccent01, CarbonColors.gray20);
    expect(CarbonThemeData.gray10.layerAccentActive01, CarbonColors.gray40);
    expect(CarbonThemeData.gray10.layerAccentHover01, CarbonColors.gray20Hover);
    expect(CarbonThemeData.gray10.layerAccent02, CarbonColors.gray20);
    expect(CarbonThemeData.gray10.layerAccentActive02, CarbonColors.gray40);
    expect(CarbonThemeData.gray10.layerAccentHover02, CarbonColors.gray20Hover);
    expect(CarbonThemeData.gray10.layerAccent03, CarbonColors.gray20);
    expect(CarbonThemeData.gray10.layerAccentActive03, CarbonColors.gray40);
    expect(CarbonThemeData.gray10.layerAccentHover03, CarbonColors.gray20Hover);
    expect(CarbonThemeData.gray10.field01, CarbonColors.white);
    expect(CarbonThemeData.gray10.fieldHover01, CarbonColors.whiteHover);
    expect(CarbonThemeData.gray10.field02, CarbonColors.gray10);
    expect(CarbonThemeData.gray10.fieldHover02, CarbonColors.gray10Hover);
    expect(CarbonThemeData.gray10.field03, CarbonColors.white);
    expect(CarbonThemeData.gray10.fieldHover03, CarbonColors.whiteHover);
    expect(CarbonThemeData.gray10.borderSubtle00, CarbonColors.gray30);
    expect(CarbonThemeData.gray10.borderSubtle01, CarbonColors.gray20);
    expect(CarbonThemeData.gray10.borderSubtleSelected01, CarbonColors.gray30);
    expect(CarbonThemeData.gray10.borderSubtle02, CarbonColors.gray30);
    expect(CarbonThemeData.gray10.borderSubtleSelected02, CarbonColors.gray30);
    expect(CarbonThemeData.gray10.borderSubtle03, CarbonColors.gray20);
    expect(CarbonThemeData.gray10.borderSubtleSelected03, CarbonColors.gray30);
    expect(CarbonThemeData.gray10.borderStrong01, CarbonColors.gray50);
    expect(CarbonThemeData.gray10.borderStrong02, CarbonColors.gray50);
    expect(CarbonThemeData.gray10.borderStrong03, CarbonColors.gray50);
    expect(CarbonThemeData.gray10.borderTile01, CarbonColors.gray40);
    expect(CarbonThemeData.gray10.borderTile02, CarbonColors.gray30);
    expect(CarbonThemeData.gray10.borderTile03, CarbonColors.gray40);
    expect(CarbonThemeData.gray10.borderInverse, CarbonColors.gray100);
    expect(CarbonThemeData.gray10.borderInteractive, CarbonColors.blue60);
    expect(CarbonThemeData.gray10.borderDisabled, CarbonColors.gray30);
    expect(CarbonThemeData.gray10.textPrimary, CarbonColors.gray100);
    expect(CarbonThemeData.gray10.textSecondary, CarbonColors.gray70);
    expect(
      CarbonThemeData.gray10.textPlaceholder,
      _alpha(CarbonColors.gray100, 0.4),
    );
    expect(CarbonThemeData.gray10.textHelper, CarbonColors.gray60);
    expect(CarbonThemeData.gray10.textError, CarbonColors.red60);
    expect(CarbonThemeData.gray10.textInverse, CarbonColors.white);
    expect(CarbonThemeData.gray10.textOnColor, CarbonColors.white);
    expect(CarbonThemeData.gray10.textOnColorDisabled, CarbonColors.gray50);
    expect(
      CarbonThemeData.gray10.textDisabled,
      _alpha(CarbonColors.gray100, 0.25),
    );
    expect(CarbonThemeData.gray10.linkPrimary, CarbonColors.blue60);
    expect(CarbonThemeData.gray10.linkPrimaryHover, CarbonColors.blue70);
    expect(CarbonThemeData.gray10.linkSecondary, CarbonColors.blue70);
    expect(CarbonThemeData.gray10.linkInverse, CarbonColors.blue40);
    expect(CarbonThemeData.gray10.linkVisited, CarbonColors.purple60);
    expect(CarbonThemeData.gray10.linkInverseVisited, CarbonColors.purple40);
    expect(CarbonThemeData.gray10.linkInverseActive, CarbonColors.gray10);
    expect(CarbonThemeData.gray10.linkInverseHover, CarbonColors.blue30);
    expect(CarbonThemeData.gray10.iconPrimary, CarbonColors.gray100);
    expect(CarbonThemeData.gray10.iconSecondary, CarbonColors.gray70);
    expect(CarbonThemeData.gray10.iconInverse, CarbonColors.white);
    expect(CarbonThemeData.gray10.iconOnColor, CarbonColors.white);
    expect(CarbonThemeData.gray10.iconOnColorDisabled, CarbonColors.gray50);
    expect(
      CarbonThemeData.gray10.iconDisabled,
      _alpha(CarbonColors.gray100, 0.25),
    );
    expect(CarbonThemeData.gray10.iconInteractive, CarbonColors.blue60);
    expect(CarbonThemeData.gray10.supportError, CarbonColors.red60);
    expect(CarbonThemeData.gray10.supportSuccess, CarbonColors.green50);
    expect(CarbonThemeData.gray10.supportWarning, CarbonColors.yellow30);
    expect(CarbonThemeData.gray10.supportInfo, CarbonColors.blue70);
    expect(CarbonThemeData.gray10.supportErrorInverse, CarbonColors.red50);
    expect(CarbonThemeData.gray10.supportSuccessInverse, CarbonColors.green40);
    expect(CarbonThemeData.gray10.supportWarningInverse, CarbonColors.yellow30);
    expect(CarbonThemeData.gray10.supportInfoInverse, CarbonColors.blue50);
    expect(CarbonThemeData.gray10.supportCautionMinor, CarbonColors.yellow30);
    expect(CarbonThemeData.gray10.supportCautionMajor, CarbonColors.orange40);
    expect(
      CarbonThemeData.gray10.supportCautionUndefined,
      CarbonColors.purple60,
    );
    expect(CarbonThemeData.gray10.focus, CarbonColors.blue60);
    expect(CarbonThemeData.gray10.focusInset, CarbonColors.white);
    expect(CarbonThemeData.gray10.focusInverse, CarbonColors.white);
    expect(CarbonThemeData.gray10.skeletonBackground, CarbonColors.gray10Hover);
    expect(CarbonThemeData.gray10.skeletonElement, CarbonColors.gray30);
    expect(CarbonThemeData.gray10.interactive, CarbonColors.blue60);
    expect(CarbonThemeData.gray10.highlight, CarbonColors.blue20);
    expect(CarbonThemeData.gray10.overlay, _alpha(CarbonColors.black, 0.6));
    expect(CarbonThemeData.gray10.toggleOff, CarbonColors.gray50);
    expect(CarbonThemeData.gray10.shadow, const Color.fromRGBO(0, 0, 0, 0.3));
  });

  test('gray90 theme tokens match the Carbon source', () {
    expect(CarbonThemeData.gray90.brightness, Brightness.dark);
    expect(CarbonThemeData.gray90.background, CarbonColors.gray90);
    expect(CarbonThemeData.gray90.backgroundInverse, CarbonColors.gray10);
    expect(CarbonThemeData.gray90.backgroundBrand, CarbonColors.blue60);
    expect(
      CarbonThemeData.gray90.backgroundActive,
      _alpha(CarbonColors.gray50, 0.4),
    );
    expect(
      CarbonThemeData.gray90.backgroundHover,
      _alpha(CarbonColors.gray50, 0.16),
    );
    expect(
      CarbonThemeData.gray90.backgroundInverseHover,
      CarbonColors.gray10Hover,
    );
    expect(
      CarbonThemeData.gray90.backgroundSelected,
      _alpha(CarbonColors.gray50, 0.24),
    );
    expect(
      CarbonThemeData.gray90.backgroundSelectedHover,
      _alpha(CarbonColors.gray50, 0.32),
    );
    expect(CarbonThemeData.gray90.layer01, CarbonColors.gray80);
    expect(CarbonThemeData.gray90.layerActive01, CarbonColors.gray60);
    expect(CarbonThemeData.gray90.layerBackground01, CarbonColors.gray90);
    expect(CarbonThemeData.gray90.layerHover01, CarbonColors.gray80Hover);
    expect(CarbonThemeData.gray90.layerSelected01, CarbonColors.gray70);
    expect(
      CarbonThemeData.gray90.layerSelectedHover01,
      CarbonColors.gray70Hover,
    );
    expect(CarbonThemeData.gray90.layer02, CarbonColors.gray70);
    expect(CarbonThemeData.gray90.layerActive02, CarbonColors.gray50);
    expect(CarbonThemeData.gray90.layerBackground02, CarbonColors.gray80);
    expect(CarbonThemeData.gray90.layerHover02, CarbonColors.gray70Hover);
    expect(CarbonThemeData.gray90.layerSelected02, CarbonColors.gray60);
    expect(
      CarbonThemeData.gray90.layerSelectedHover02,
      CarbonColors.gray60Hover,
    );
    expect(CarbonThemeData.gray90.layer03, CarbonColors.gray60);
    expect(CarbonThemeData.gray90.layerActive03, CarbonColors.gray80);
    expect(CarbonThemeData.gray90.layerBackground03, CarbonColors.gray70);
    expect(CarbonThemeData.gray90.layerHover03, CarbonColors.gray60Hover);
    expect(CarbonThemeData.gray90.layerSelected03, CarbonColors.gray70);
    expect(
      CarbonThemeData.gray90.layerSelectedHover03,
      CarbonColors.gray70Hover,
    );
    expect(CarbonThemeData.gray90.layerSelectedInverse, CarbonColors.gray10);
    expect(CarbonThemeData.gray90.layerSelectedDisabled, CarbonColors.gray40);
    expect(CarbonThemeData.gray90.layerAccent01, CarbonColors.gray70);
    expect(CarbonThemeData.gray90.layerAccentActive01, CarbonColors.gray50);
    expect(CarbonThemeData.gray90.layerAccentHover01, CarbonColors.gray70Hover);
    expect(CarbonThemeData.gray90.layerAccent02, CarbonColors.gray60);
    expect(CarbonThemeData.gray90.layerAccentActive02, CarbonColors.gray80);
    expect(CarbonThemeData.gray90.layerAccentHover02, CarbonColors.gray60Hover);
    expect(CarbonThemeData.gray90.layerAccent03, CarbonColors.gray50);
    expect(CarbonThemeData.gray90.layerAccentActive03, CarbonColors.gray70);
    expect(CarbonThemeData.gray90.layerAccentHover03, CarbonColors.gray50Hover);
    expect(CarbonThemeData.gray90.field01, CarbonColors.gray80);
    expect(CarbonThemeData.gray90.fieldHover01, CarbonColors.gray80Hover);
    expect(CarbonThemeData.gray90.field02, CarbonColors.gray70);
    expect(CarbonThemeData.gray90.fieldHover02, CarbonColors.gray70Hover);
    expect(CarbonThemeData.gray90.field03, CarbonColors.gray60);
    expect(CarbonThemeData.gray90.fieldHover03, CarbonColors.gray60Hover);
    expect(CarbonThemeData.gray90.borderSubtle00, CarbonColors.gray70);
    expect(CarbonThemeData.gray90.borderSubtle01, CarbonColors.gray60);
    expect(CarbonThemeData.gray90.borderSubtleSelected01, CarbonColors.gray50);
    expect(CarbonThemeData.gray90.borderSubtle02, CarbonColors.gray50);
    expect(CarbonThemeData.gray90.borderSubtleSelected02, CarbonColors.gray40);
    expect(CarbonThemeData.gray90.borderSubtle03, CarbonColors.gray50);
    expect(CarbonThemeData.gray90.borderSubtleSelected03, CarbonColors.gray40);
    expect(CarbonThemeData.gray90.borderStrong01, CarbonColors.gray50);
    expect(CarbonThemeData.gray90.borderStrong02, CarbonColors.gray40);
    expect(CarbonThemeData.gray90.borderStrong03, CarbonColors.gray30);
    expect(CarbonThemeData.gray90.borderTile01, CarbonColors.gray60);
    expect(CarbonThemeData.gray90.borderTile02, CarbonColors.gray50);
    expect(CarbonThemeData.gray90.borderTile03, CarbonColors.gray40);
    expect(CarbonThemeData.gray90.borderInverse, CarbonColors.gray10);
    expect(CarbonThemeData.gray90.borderInteractive, CarbonColors.blue50);
    expect(
      CarbonThemeData.gray90.borderDisabled,
      _alpha(CarbonColors.gray50, 0.5),
    );
    expect(CarbonThemeData.gray90.textPrimary, CarbonColors.gray10);
    expect(CarbonThemeData.gray90.textSecondary, CarbonColors.gray30);
    expect(
      CarbonThemeData.gray90.textPlaceholder,
      _alpha(CarbonColors.gray10, 0.4),
    );
    expect(CarbonThemeData.gray90.textHelper, CarbonColors.gray30);
    expect(CarbonThemeData.gray90.textError, CarbonColors.red30);
    expect(CarbonThemeData.gray90.textInverse, CarbonColors.gray100);
    expect(CarbonThemeData.gray90.textOnColor, CarbonColors.white);
    expect(
      CarbonThemeData.gray90.textOnColorDisabled,
      _alpha(CarbonColors.white, 0.25),
    );
    expect(
      CarbonThemeData.gray90.textDisabled,
      _alpha(CarbonColors.gray10, 0.25),
    );
    expect(CarbonThemeData.gray90.linkPrimary, CarbonColors.blue40);
    expect(CarbonThemeData.gray90.linkPrimaryHover, CarbonColors.blue30);
    expect(CarbonThemeData.gray90.linkSecondary, CarbonColors.blue30);
    expect(CarbonThemeData.gray90.linkInverse, CarbonColors.blue60);
    expect(CarbonThemeData.gray90.linkVisited, CarbonColors.purple40);
    expect(CarbonThemeData.gray90.linkInverseVisited, CarbonColors.purple60);
    expect(CarbonThemeData.gray90.linkInverseActive, CarbonColors.gray100);
    expect(CarbonThemeData.gray90.linkInverseHover, CarbonColors.blue70);
    expect(CarbonThemeData.gray90.iconPrimary, CarbonColors.gray10);
    expect(CarbonThemeData.gray90.iconSecondary, CarbonColors.gray30);
    expect(CarbonThemeData.gray90.iconInverse, CarbonColors.gray100);
    expect(CarbonThemeData.gray90.iconOnColor, CarbonColors.white);
    expect(
      CarbonThemeData.gray90.iconOnColorDisabled,
      _alpha(CarbonColors.white, 0.25),
    );
    expect(
      CarbonThemeData.gray90.iconDisabled,
      _alpha(CarbonColors.gray10, 0.25),
    );
    expect(CarbonThemeData.gray90.iconInteractive, CarbonColors.white);
    expect(CarbonThemeData.gray90.supportError, CarbonColors.red40);
    expect(CarbonThemeData.gray90.supportSuccess, CarbonColors.green40);
    expect(CarbonThemeData.gray90.supportWarning, CarbonColors.yellow30);
    expect(CarbonThemeData.gray90.supportInfo, CarbonColors.blue50);
    expect(CarbonThemeData.gray90.supportErrorInverse, CarbonColors.red60);
    expect(CarbonThemeData.gray90.supportSuccessInverse, CarbonColors.green50);
    expect(CarbonThemeData.gray90.supportWarningInverse, CarbonColors.yellow30);
    expect(CarbonThemeData.gray90.supportInfoInverse, CarbonColors.blue70);
    expect(CarbonThemeData.gray90.supportCautionMinor, CarbonColors.yellow30);
    expect(CarbonThemeData.gray90.supportCautionMajor, CarbonColors.orange40);
    expect(
      CarbonThemeData.gray90.supportCautionUndefined,
      CarbonColors.purple50,
    );
    expect(CarbonThemeData.gray90.focus, CarbonColors.white);
    expect(CarbonThemeData.gray90.focusInset, CarbonColors.gray100);
    expect(CarbonThemeData.gray90.focusInverse, CarbonColors.blue60);
    expect(CarbonThemeData.gray90.skeletonBackground, CarbonColors.gray90Hover);
    expect(CarbonThemeData.gray90.skeletonElement, CarbonColors.gray70);
    expect(CarbonThemeData.gray90.interactive, CarbonColors.blue50);
    expect(CarbonThemeData.gray90.highlight, CarbonColors.blue80);
    expect(CarbonThemeData.gray90.overlay, _alpha(CarbonColors.black, 0.6));
    expect(CarbonThemeData.gray90.toggleOff, CarbonColors.gray50);
    expect(CarbonThemeData.gray90.shadow, _alpha(CarbonColors.black, 0.8));
  });

  test('gray100 theme tokens match the Carbon source', () {
    expect(CarbonThemeData.gray100.brightness, Brightness.dark);
    expect(CarbonThemeData.gray100.background, CarbonColors.gray100);
    expect(CarbonThemeData.gray100.backgroundInverse, CarbonColors.gray10);
    expect(CarbonThemeData.gray100.backgroundBrand, CarbonColors.blue60);
    expect(
      CarbonThemeData.gray100.backgroundActive,
      _alpha(CarbonColors.gray50, 0.4),
    );
    expect(
      CarbonThemeData.gray100.backgroundHover,
      _alpha(CarbonColors.gray50, 0.16),
    );
    expect(
      CarbonThemeData.gray100.backgroundInverseHover,
      CarbonColors.gray10Hover,
    );
    expect(
      CarbonThemeData.gray100.backgroundSelected,
      _alpha(CarbonColors.gray50, 0.24),
    );
    expect(
      CarbonThemeData.gray100.backgroundSelectedHover,
      _alpha(CarbonColors.gray50, 0.32),
    );
    expect(CarbonThemeData.gray100.layer01, CarbonColors.gray90);
    expect(CarbonThemeData.gray100.layerActive01, CarbonColors.gray70);
    expect(CarbonThemeData.gray100.layerBackground01, CarbonColors.gray100);
    expect(CarbonThemeData.gray100.layerHover01, CarbonColors.gray90Hover);
    expect(CarbonThemeData.gray100.layerSelected01, CarbonColors.gray80);
    expect(
      CarbonThemeData.gray100.layerSelectedHover01,
      CarbonColors.gray80Hover,
    );
    expect(CarbonThemeData.gray100.layer02, CarbonColors.gray80);
    expect(CarbonThemeData.gray100.layerActive02, CarbonColors.gray60);
    expect(CarbonThemeData.gray100.layerBackground02, CarbonColors.gray90);
    expect(CarbonThemeData.gray100.layerHover02, CarbonColors.gray80Hover);
    expect(CarbonThemeData.gray100.layerSelected02, CarbonColors.gray70);
    expect(
      CarbonThemeData.gray100.layerSelectedHover02,
      CarbonColors.gray70Hover,
    );
    expect(CarbonThemeData.gray100.layer03, CarbonColors.gray70);
    expect(CarbonThemeData.gray100.layerActive03, CarbonColors.gray50);
    expect(CarbonThemeData.gray100.layerBackground03, CarbonColors.gray80);
    expect(CarbonThemeData.gray100.layerHover03, CarbonColors.gray70Hover);
    expect(CarbonThemeData.gray100.layerSelected03, CarbonColors.gray60);
    expect(
      CarbonThemeData.gray100.layerSelectedHover03,
      CarbonColors.gray60Hover,
    );
    expect(CarbonThemeData.gray100.layerSelectedInverse, CarbonColors.gray10);
    expect(CarbonThemeData.gray100.layerSelectedDisabled, CarbonColors.gray40);
    expect(CarbonThemeData.gray100.layerAccent01, CarbonColors.gray80);
    expect(CarbonThemeData.gray100.layerAccentActive01, CarbonColors.gray60);
    expect(
      CarbonThemeData.gray100.layerAccentHover01,
      CarbonColors.gray80Hover,
    );
    expect(CarbonThemeData.gray100.layerAccent02, CarbonColors.gray70);
    expect(CarbonThemeData.gray100.layerAccentActive02, CarbonColors.gray50);
    expect(
      CarbonThemeData.gray100.layerAccentHover02,
      CarbonColors.gray70Hover,
    );
    expect(CarbonThemeData.gray100.layerAccent03, CarbonColors.gray60);
    expect(CarbonThemeData.gray100.layerAccentActive03, CarbonColors.gray80);
    expect(
      CarbonThemeData.gray100.layerAccentHover03,
      CarbonColors.gray60Hover,
    );
    expect(CarbonThemeData.gray100.field01, CarbonColors.gray90);
    expect(CarbonThemeData.gray100.fieldHover01, CarbonColors.gray90Hover);
    expect(CarbonThemeData.gray100.field02, CarbonColors.gray80);
    expect(CarbonThemeData.gray100.fieldHover02, CarbonColors.gray80Hover);
    expect(CarbonThemeData.gray100.field03, CarbonColors.gray70);
    expect(CarbonThemeData.gray100.fieldHover03, CarbonColors.gray70Hover);
    expect(CarbonThemeData.gray100.borderSubtle00, CarbonColors.gray80);
    expect(CarbonThemeData.gray100.borderSubtle01, CarbonColors.gray70);
    expect(CarbonThemeData.gray100.borderSubtleSelected01, CarbonColors.gray60);
    expect(CarbonThemeData.gray100.borderSubtle02, CarbonColors.gray60);
    expect(CarbonThemeData.gray100.borderSubtleSelected02, CarbonColors.gray50);
    expect(CarbonThemeData.gray100.borderSubtle03, CarbonColors.gray60);
    expect(CarbonThemeData.gray100.borderSubtleSelected03, CarbonColors.gray50);
    expect(CarbonThemeData.gray100.borderStrong01, CarbonColors.gray60);
    expect(CarbonThemeData.gray100.borderStrong02, CarbonColors.gray50);
    expect(CarbonThemeData.gray100.borderStrong03, CarbonColors.gray40);
    expect(CarbonThemeData.gray100.borderTile01, CarbonColors.gray70);
    expect(CarbonThemeData.gray100.borderTile02, CarbonColors.gray60);
    expect(CarbonThemeData.gray100.borderTile03, CarbonColors.gray50);
    expect(CarbonThemeData.gray100.borderInverse, CarbonColors.gray10);
    expect(CarbonThemeData.gray100.borderInteractive, CarbonColors.blue50);
    expect(
      CarbonThemeData.gray100.borderDisabled,
      _alpha(CarbonColors.gray50, 0.5),
    );
    expect(CarbonThemeData.gray100.textPrimary, CarbonColors.gray10);
    expect(CarbonThemeData.gray100.textSecondary, CarbonColors.gray30);
    expect(
      CarbonThemeData.gray100.textPlaceholder,
      _alpha(CarbonColors.gray10, 0.4),
    );
    expect(CarbonThemeData.gray100.textHelper, CarbonColors.gray40);
    expect(CarbonThemeData.gray100.textError, CarbonColors.red40);
    expect(CarbonThemeData.gray100.textInverse, CarbonColors.gray100);
    expect(CarbonThemeData.gray100.textOnColor, CarbonColors.white);
    expect(
      CarbonThemeData.gray100.textOnColorDisabled,
      _alpha(CarbonColors.white, 0.25),
    );
    expect(
      CarbonThemeData.gray100.textDisabled,
      _alpha(CarbonColors.gray10, 0.25),
    );
    expect(CarbonThemeData.gray100.linkPrimary, CarbonColors.blue40);
    expect(CarbonThemeData.gray100.linkPrimaryHover, CarbonColors.blue30);
    expect(CarbonThemeData.gray100.linkSecondary, CarbonColors.blue30);
    expect(CarbonThemeData.gray100.linkInverse, CarbonColors.blue60);
    expect(CarbonThemeData.gray100.linkVisited, CarbonColors.purple40);
    expect(CarbonThemeData.gray100.linkInverseVisited, CarbonColors.purple60);
    expect(CarbonThemeData.gray100.linkInverseActive, CarbonColors.gray100);
    expect(CarbonThemeData.gray100.linkInverseHover, CarbonColors.blue70);
    expect(CarbonThemeData.gray100.iconPrimary, CarbonColors.gray10);
    expect(CarbonThemeData.gray100.iconSecondary, CarbonColors.gray30);
    expect(CarbonThemeData.gray100.iconInverse, CarbonColors.gray100);
    expect(CarbonThemeData.gray100.iconOnColor, CarbonColors.white);
    expect(
      CarbonThemeData.gray100.iconOnColorDisabled,
      _alpha(CarbonColors.white, 0.25),
    );
    expect(
      CarbonThemeData.gray100.iconDisabled,
      _alpha(CarbonColors.gray10, 0.25),
    );
    expect(CarbonThemeData.gray100.iconInteractive, CarbonColors.white);
    expect(CarbonThemeData.gray100.supportError, CarbonColors.red50);
    expect(CarbonThemeData.gray100.supportSuccess, CarbonColors.green40);
    expect(CarbonThemeData.gray100.supportWarning, CarbonColors.yellow30);
    expect(CarbonThemeData.gray100.supportInfo, CarbonColors.blue50);
    expect(CarbonThemeData.gray100.supportErrorInverse, CarbonColors.red60);
    expect(CarbonThemeData.gray100.supportSuccessInverse, CarbonColors.green50);
    expect(
      CarbonThemeData.gray100.supportWarningInverse,
      CarbonColors.yellow30,
    );
    expect(CarbonThemeData.gray100.supportInfoInverse, CarbonColors.blue70);
    expect(CarbonThemeData.gray100.supportCautionMinor, CarbonColors.yellow30);
    expect(CarbonThemeData.gray100.supportCautionMajor, CarbonColors.orange40);
    expect(
      CarbonThemeData.gray100.supportCautionUndefined,
      CarbonColors.purple50,
    );
    expect(CarbonThemeData.gray100.focus, CarbonColors.white);
    expect(CarbonThemeData.gray100.focusInset, CarbonColors.gray100);
    expect(CarbonThemeData.gray100.focusInverse, CarbonColors.blue60);
    expect(CarbonThemeData.gray100.skeletonBackground, const Color(0xFF292929));
    expect(CarbonThemeData.gray100.skeletonElement, CarbonColors.gray80);
    expect(CarbonThemeData.gray100.interactive, CarbonColors.blue50);
    expect(CarbonThemeData.gray100.highlight, CarbonColors.blue90);
    expect(CarbonThemeData.gray100.overlay, _alpha(CarbonColors.black, 0.6));
    expect(CarbonThemeData.gray100.toggleOff, CarbonColors.gray60);
    expect(CarbonThemeData.gray100.shadow, _alpha(CarbonColors.black, 0.8));
  });

  test('themes carry the expected brightness', () {
    expect(CarbonThemeData.white.brightness, Brightness.light);
    expect(CarbonThemeData.gray10.brightness, Brightness.light);
    expect(CarbonThemeData.gray90.brightness, Brightness.dark);
    expect(CarbonThemeData.gray100.brightness, Brightness.dark);
  });

  test('themes are distinct', () {
    expect(
      CarbonThemeData.white.background,
      isNot(CarbonThemeData.gray100.background),
    );
    expect(
      CarbonThemeData.gray90.layer01,
      isNot(CarbonThemeData.gray100.layer01),
    );
  });
}
