#!/usr/bin/env python3
"""Generate Carbide's theme tokens from the pinned Carbon source.

Reads the four Carbon theme files (Apache-2.0) and emits:
  - lib/src/theme/carbon_theme_data.dart   (`CarbonThemeData` + 4 built-ins)
  - test/theme/carbon_theme_data_test.dart (an exhaustive value lock)

Only the core semantic color tokens are ported: the region from `colorScheme`
up to (but not including) the syntax-highlighting section. Syntax-highlighting,
AI-experimental, and chat tokens, plus the type/layout re-exports, are out of
scope here (tracked by their own issues/milestones).

Run from the repository root:  python3 tool/generate_carbon_themes.py
Re-run when bumping the Carbon submodule; review the diff.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COLORS_SRC = ROOT / "documentation/carbon/packages/colors/src/colors.ts"
THEME_DIR = ROOT / "documentation/carbon/packages/themes/src"
THEMES = {"white": "white", "gray10": "g10", "gray90": "g90", "gray100": "g100"}
TITLES = {"white": "White", "gray10": "Gray 10", "gray90": "Gray 90", "gray100": "Gray 100"}
LIB_OUT = ROOT / "lib/src/theme/carbon_theme_data.dart"
TEST_OUT = ROOT / "test/theme/carbon_theme_data_test.dart"

EXPORT = re.compile(r"^export const (\w+) = (.+);$", re.M)
ALPHA_CALL = re.compile(r"^(?:adjustAlpha|rgba)\(\s*(\w+)\s*,\s*([\d.]+)\s*\)$")
LIGHTNESS = re.compile(r"^adjustLightness\(\s*(\w+)\s*,\s*(-?[\d.]+)\s*\)$")
RGBA_STR = re.compile(r"^'rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)'$")

HEADER = """// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the GNU Affero General
// Public License v3.0 or later. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_themes.py — do not edit by hand.
//
// Semantic token values are ported verbatim from the Apache-2.0 licensed Carbon
// Design System (@carbon/themes). See the NOTICE file for attribution.
"""


def color_values() -> dict[str, str]:
    """Map every Carbon color name to its `RRGGBB` hex (aliases resolved)."""
    text = COLORS_SRC.read_text()
    values: dict[str, str] = {}
    for line in text.splitlines():
        m = re.match(r"^export const (\w+) = '#([0-9a-fA-F]{6})';$", line)
        if m:
            values[m.group(1)] = m.group(2).upper()
            continue
        m = re.match(r"^export const (\w+) = (\w+);$", line)
        if m and m.group(2) in values:
            values[m.group(1)] = values[m.group(2)]
    return values


def adjust_lightness(hexv: str, shift: float) -> str:
    """Replicate @carbon/themes `adjustLightness` (via the JS `color` lib).

    The key subtlety is that the lib rounds the HSL channels *before* converting
    back to RGB, so a naive HSLColor round-trip would differ by one step.
    """
    r, g, b = (int(hexv[i : i + 2], 16) / 255 for i in (0, 2, 4))
    high, low = max(r, g, b), min(r, g, b)
    lightness = (high + low) / 2
    saturation = 0.0
    hue = 0.0
    if high != low:
        delta = high - low
        saturation = (
            delta / (2 - high - low) if lightness > 0.5 else delta / (high + low)
        )
        if high == r:
            hue = (g - b) / delta + (6 if g < b else 0)
        elif high == g:
            hue = (b - r) / delta + 2
        else:
            hue = (r - g) / delta + 4
        hue /= 6
    hue, saturation, lightness = (
        round(hue * 360),
        round(saturation * 100),
        round(lightness * 100 + shift),
    )
    h, s, light = hue / 360, saturation / 100, lightness / 100
    if s == 0:
        channels = [light, light, light]
    else:
        q = light * (1 + s) if light < 0.5 else light + s - light * s
        p = 2 * light - q
        channels = []
        for t in (h + 1 / 3, h, h - 1 / 3):
            t = t % 1
            if t < 1 / 6:
                channels.append(p + (q - p) * 6 * t)
            elif t < 1 / 2:
                channels.append(q)
            elif t < 2 / 3:
                channels.append(p + (q - p) * (2 / 3 - t) * 6)
            else:
                channels.append(p)
    return "".join(f"{round(c * 255):02X}" for c in channels)


def core_region(theme_file: Path) -> dict[str, str]:
    text = theme_file.read_text()
    region = text[: text.index("// Syntax highlighting")]
    return {m.group(1): m.group(2).strip() for m in EXPORT.finditer(region)}


def num(value: str) -> str:
    return value if "." in value else f"{value}.0"


def resolve(expr, tokens, colors, values) -> str:
    m = RGBA_STR.match(expr)
    if m:
        r, g, b, a = m.groups()
        return f"const Color.fromRGBO({r}, {g}, {b}, {num(a)})"
    m = LIGHTNESS.match(expr)
    if m:
        base = resolve_color(m.group(1), tokens, colors, values)
        hexv = values[base.split(".")[1]]
        return f"const Color(0xFF{adjust_lightness(hexv, float(m.group(2)))})"
    m = ALPHA_CALL.match(expr)
    if m:
        base = resolve_color(m.group(1), tokens, colors, values)
        return f"_alpha({base}, {num(m.group(2))})"
    if re.fullmatch(r"\w+", expr):
        return resolve_color(expr, tokens, colors, values)
    raise ValueError(f"unhandled expr: {expr}")


def resolve_color(ident, tokens, colors, values) -> str:
    if ident in colors:
        return f"CarbonColors.{ident}"
    if ident in tokens:
        resolved = resolve(tokens[ident], tokens, colors, values)
        assert resolved.startswith("CarbonColors."), (
            f"expected {ident} to resolve to a plain color, got {resolved}"
        )
        return resolved
    raise ValueError(f"unknown identifier: {ident}")


def section_of(name: str) -> str:
    match = re.match(r"^[a-z]+", name)
    return match.group(0) if match else name


def build():
    colors = set(color_values())
    values = color_values()
    raw: dict[str, dict[str, str]] = {}
    brightness: dict[str, str] = {}
    for field, slug in THEMES.items():
        region = core_region(THEME_DIR / f"{slug}.ts")
        brightness[field] = "light" if region.pop("colorScheme").strip("'") == "light" else "dark"
        raw[field] = region

    order = list(raw["white"])
    for field, region in raw.items():
        assert set(region) == set(order), f"{field} token set differs"

    resolved = {
        field: {n: resolve(region[n], region, colors, values) for n in order}
        for field, region in raw.items()
    }
    return order, brightness, resolved


def emit_lib(order, brightness, resolved) -> str:
    lines = [
        HEADER,
        "import 'dart:ui' show Brightness, Color;",
        "",
        "import 'package:flutter/foundation.dart' show immutable;",
        "",
        "import '../foundations/colors.dart';",
        "",
        "/// The resolved semantic color tokens for one Carbon theme.",
        "///",
        "/// Carbon ships four themes — [white], [gray10], [gray90], and",
        "/// [gray100] — each mapping the same set of semantic tokens",
        "/// (background, layer, field, text, support, …) onto the palette. Use",
        "/// a built-in, or construct a custom theme with the constructor.",
        "@immutable",
        "class CarbonThemeData {",
        "  /// Creates a theme from an explicit set of semantic tokens.",
        "  const CarbonThemeData({",
        "    required this.brightness,",
    ]
    lines += [f"    required this.{n}," for n in order]
    lines.append("  });")
    lines.append("")
    lines.append("  /// Whether this is a light or dark theme.")
    lines.append("  final Brightness brightness;")
    section = None
    for n in order:
        if section_of(n) != section:
            section = section_of(n)
            lines.append("")
        lines.append(f"  /// The `{n}` token.")
        lines.append(f"  final Color {n};")
    lines.append("")
    for field in THEMES:
        lines.append(f"  /// The {TITLES[field]} theme.")
        lines.append(f"  static final CarbonThemeData {field} = CarbonThemeData(")
        lines.append(f"    brightness: Brightness.{brightness[field]},")
        lines += [f"    {n}: {resolved[field][n]}," for n in order]
        lines.append("  );")
        lines.append("")
    lines.append("}")
    lines.append("")
    lines.append("Color _alpha(Color color, double opacity) =>")
    lines.append("    color.withValues(alpha: opacity);")
    lines.append("")
    return "\n".join(lines)


def emit_test(order, brightness, resolved) -> str:
    lines = [
        "// Copyright 2026 Bizjak Tech OÜ",
        "//",
        "// This file is part of Carbide and is licensed under the GNU Affero",
        "// General Public License v3.0 or later. See the LICENSE file in the",
        "// project root.",
        "//",
        "// GENERATED by tool/generate_carbon_themes.py — do not edit by hand.",
        "",
        "import 'dart:ui';",
        "",
        "import 'package:carbide/carbide.dart';",
        "import 'package:flutter_test/flutter_test.dart';",
        "",
        "Color _alpha(Color color, double opacity) =>",
        "    color.withValues(alpha: opacity);",
        "",
        "void main() {",
    ]
    for field in THEMES:
        lines.append(f"  test('{field} theme tokens match the Carbon source', () {{")
        lines.append(
            f"    expect(CarbonThemeData.{field}.brightness, "
            f"Brightness.{brightness[field]});"
        )
        lines += [
            f"    expect(CarbonThemeData.{field}.{n}, {resolved[field][n]});"
            for n in order
        ]
        lines.append("  });")
        lines.append("")
    lines += [
        "  test('themes carry the expected brightness', () {",
        "    expect(CarbonThemeData.white.brightness, Brightness.light);",
        "    expect(CarbonThemeData.gray10.brightness, Brightness.light);",
        "    expect(CarbonThemeData.gray90.brightness, Brightness.dark);",
        "    expect(CarbonThemeData.gray100.brightness, Brightness.dark);",
        "  });",
        "",
        "  test('themes are distinct', () {",
        "    expect(CarbonThemeData.white.background, "
        "isNot(CarbonThemeData.gray100.background));",
        "    expect(CarbonThemeData.gray90.layer01, "
        "isNot(CarbonThemeData.gray100.layer01));",
        "  });",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    order, brightness, resolved = build()
    LIB_OUT.write_text(emit_lib(order, brightness, resolved))
    TEST_OUT.write_text(emit_test(order, brightness, resolved))
    print(f"parsed {len(order)} semantic tokens across {len(THEMES)} themes")
    print(f"wrote {LIB_OUT.relative_to(ROOT)} and {TEST_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
