// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the GNU Affero General
// Public License v3.0 or later. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_themes.py — do not edit by hand.
//
// Semantic token values are ported verbatim from the Apache-2.0 licensed Carbon
// Design System (@carbon/themes). See the NOTICE file for attribution.

import 'dart:ui' show Brightness, Color;

import 'package:flutter/foundation.dart' show immutable;

import '../foundations/colors.dart';

/// The resolved semantic color tokens for one Carbon theme.
///
/// Carbon ships four themes — [white], [gray10], [gray90], and
/// [gray100] — each mapping the same set of semantic tokens
/// (background, layer, field, text, support, …) onto the palette. Use
/// a built-in, or construct a custom theme with the constructor.
@immutable
class CarbonThemeData {
  /// Creates a theme from an explicit set of semantic tokens.
  const CarbonThemeData({
    required this.brightness,
    required this.background,
    required this.backgroundInverse,
    required this.backgroundBrand,
    required this.backgroundActive,
    required this.backgroundHover,
    required this.backgroundInverseHover,
    required this.backgroundSelected,
    required this.backgroundSelectedHover,
    required this.layer01,
    required this.layerActive01,
    required this.layerBackground01,
    required this.layerHover01,
    required this.layerSelected01,
    required this.layerSelectedHover01,
    required this.layer02,
    required this.layerActive02,
    required this.layerBackground02,
    required this.layerHover02,
    required this.layerSelected02,
    required this.layerSelectedHover02,
    required this.layer03,
    required this.layerActive03,
    required this.layerBackground03,
    required this.layerHover03,
    required this.layerSelected03,
    required this.layerSelectedHover03,
    required this.layerSelectedInverse,
    required this.layerSelectedDisabled,
    required this.layerAccent01,
    required this.layerAccentActive01,
    required this.layerAccentHover01,
    required this.layerAccent02,
    required this.layerAccentActive02,
    required this.layerAccentHover02,
    required this.layerAccent03,
    required this.layerAccentActive03,
    required this.layerAccentHover03,
    required this.field01,
    required this.fieldHover01,
    required this.field02,
    required this.fieldHover02,
    required this.field03,
    required this.fieldHover03,
    required this.borderSubtle00,
    required this.borderSubtle01,
    required this.borderSubtleSelected01,
    required this.borderSubtle02,
    required this.borderSubtleSelected02,
    required this.borderSubtle03,
    required this.borderSubtleSelected03,
    required this.borderStrong01,
    required this.borderStrong02,
    required this.borderStrong03,
    required this.borderTile01,
    required this.borderTile02,
    required this.borderTile03,
    required this.borderInverse,
    required this.borderInteractive,
    required this.borderDisabled,
    required this.textPrimary,
    required this.textSecondary,
    required this.textPlaceholder,
    required this.textHelper,
    required this.textError,
    required this.textInverse,
    required this.textOnColor,
    required this.textOnColorDisabled,
    required this.textDisabled,
    required this.linkPrimary,
    required this.linkPrimaryHover,
    required this.linkSecondary,
    required this.linkInverse,
    required this.linkVisited,
    required this.linkInverseVisited,
    required this.linkInverseActive,
    required this.linkInverseHover,
    required this.iconPrimary,
    required this.iconSecondary,
    required this.iconInverse,
    required this.iconOnColor,
    required this.iconOnColorDisabled,
    required this.iconDisabled,
    required this.iconInteractive,
    required this.supportError,
    required this.supportSuccess,
    required this.supportWarning,
    required this.supportInfo,
    required this.supportErrorInverse,
    required this.supportSuccessInverse,
    required this.supportWarningInverse,
    required this.supportInfoInverse,
    required this.supportCautionMinor,
    required this.supportCautionMajor,
    required this.supportCautionUndefined,
    required this.focus,
    required this.focusInset,
    required this.focusInverse,
    required this.skeletonBackground,
    required this.skeletonElement,
    required this.interactive,
    required this.highlight,
    required this.overlay,
    required this.toggleOff,
    required this.shadow,
  });

  /// Whether this is a light or dark theme.
  final Brightness brightness;

  /// The `background` token.
  final Color background;

  /// The `backgroundInverse` token.
  final Color backgroundInverse;

  /// The `backgroundBrand` token.
  final Color backgroundBrand;

  /// The `backgroundActive` token.
  final Color backgroundActive;

  /// The `backgroundHover` token.
  final Color backgroundHover;

  /// The `backgroundInverseHover` token.
  final Color backgroundInverseHover;

  /// The `backgroundSelected` token.
  final Color backgroundSelected;

  /// The `backgroundSelectedHover` token.
  final Color backgroundSelectedHover;

  /// The `layer01` token.
  final Color layer01;

  /// The `layerActive01` token.
  final Color layerActive01;

  /// The `layerBackground01` token.
  final Color layerBackground01;

  /// The `layerHover01` token.
  final Color layerHover01;

  /// The `layerSelected01` token.
  final Color layerSelected01;

  /// The `layerSelectedHover01` token.
  final Color layerSelectedHover01;

  /// The `layer02` token.
  final Color layer02;

  /// The `layerActive02` token.
  final Color layerActive02;

  /// The `layerBackground02` token.
  final Color layerBackground02;

  /// The `layerHover02` token.
  final Color layerHover02;

  /// The `layerSelected02` token.
  final Color layerSelected02;

  /// The `layerSelectedHover02` token.
  final Color layerSelectedHover02;

  /// The `layer03` token.
  final Color layer03;

  /// The `layerActive03` token.
  final Color layerActive03;

  /// The `layerBackground03` token.
  final Color layerBackground03;

  /// The `layerHover03` token.
  final Color layerHover03;

  /// The `layerSelected03` token.
  final Color layerSelected03;

  /// The `layerSelectedHover03` token.
  final Color layerSelectedHover03;

  /// The `layerSelectedInverse` token.
  final Color layerSelectedInverse;

  /// The `layerSelectedDisabled` token.
  final Color layerSelectedDisabled;

  /// The `layerAccent01` token.
  final Color layerAccent01;

  /// The `layerAccentActive01` token.
  final Color layerAccentActive01;

  /// The `layerAccentHover01` token.
  final Color layerAccentHover01;

  /// The `layerAccent02` token.
  final Color layerAccent02;

  /// The `layerAccentActive02` token.
  final Color layerAccentActive02;

  /// The `layerAccentHover02` token.
  final Color layerAccentHover02;

  /// The `layerAccent03` token.
  final Color layerAccent03;

  /// The `layerAccentActive03` token.
  final Color layerAccentActive03;

  /// The `layerAccentHover03` token.
  final Color layerAccentHover03;

  /// The `field01` token.
  final Color field01;

  /// The `fieldHover01` token.
  final Color fieldHover01;

  /// The `field02` token.
  final Color field02;

  /// The `fieldHover02` token.
  final Color fieldHover02;

  /// The `field03` token.
  final Color field03;

  /// The `fieldHover03` token.
  final Color fieldHover03;

  /// The `borderSubtle00` token.
  final Color borderSubtle00;

  /// The `borderSubtle01` token.
  final Color borderSubtle01;

  /// The `borderSubtleSelected01` token.
  final Color borderSubtleSelected01;

  /// The `borderSubtle02` token.
  final Color borderSubtle02;

  /// The `borderSubtleSelected02` token.
  final Color borderSubtleSelected02;

  /// The `borderSubtle03` token.
  final Color borderSubtle03;

  /// The `borderSubtleSelected03` token.
  final Color borderSubtleSelected03;

  /// The `borderStrong01` token.
  final Color borderStrong01;

  /// The `borderStrong02` token.
  final Color borderStrong02;

  /// The `borderStrong03` token.
  final Color borderStrong03;

  /// The `borderTile01` token.
  final Color borderTile01;

  /// The `borderTile02` token.
  final Color borderTile02;

  /// The `borderTile03` token.
  final Color borderTile03;

  /// The `borderInverse` token.
  final Color borderInverse;

  /// The `borderInteractive` token.
  final Color borderInteractive;

  /// The `borderDisabled` token.
  final Color borderDisabled;

  /// The `textPrimary` token.
  final Color textPrimary;

  /// The `textSecondary` token.
  final Color textSecondary;

  /// The `textPlaceholder` token.
  final Color textPlaceholder;

  /// The `textHelper` token.
  final Color textHelper;

  /// The `textError` token.
  final Color textError;

  /// The `textInverse` token.
  final Color textInverse;

  /// The `textOnColor` token.
  final Color textOnColor;

  /// The `textOnColorDisabled` token.
  final Color textOnColorDisabled;

  /// The `textDisabled` token.
  final Color textDisabled;

  /// The `linkPrimary` token.
  final Color linkPrimary;

  /// The `linkPrimaryHover` token.
  final Color linkPrimaryHover;

  /// The `linkSecondary` token.
  final Color linkSecondary;

  /// The `linkInverse` token.
  final Color linkInverse;

  /// The `linkVisited` token.
  final Color linkVisited;

  /// The `linkInverseVisited` token.
  final Color linkInverseVisited;

  /// The `linkInverseActive` token.
  final Color linkInverseActive;

  /// The `linkInverseHover` token.
  final Color linkInverseHover;

  /// The `iconPrimary` token.
  final Color iconPrimary;

  /// The `iconSecondary` token.
  final Color iconSecondary;

  /// The `iconInverse` token.
  final Color iconInverse;

  /// The `iconOnColor` token.
  final Color iconOnColor;

  /// The `iconOnColorDisabled` token.
  final Color iconOnColorDisabled;

  /// The `iconDisabled` token.
  final Color iconDisabled;

  /// The `iconInteractive` token.
  final Color iconInteractive;

  /// The `supportError` token.
  final Color supportError;

  /// The `supportSuccess` token.
  final Color supportSuccess;

  /// The `supportWarning` token.
  final Color supportWarning;

  /// The `supportInfo` token.
  final Color supportInfo;

  /// The `supportErrorInverse` token.
  final Color supportErrorInverse;

  /// The `supportSuccessInverse` token.
  final Color supportSuccessInverse;

  /// The `supportWarningInverse` token.
  final Color supportWarningInverse;

  /// The `supportInfoInverse` token.
  final Color supportInfoInverse;

  /// The `supportCautionMinor` token.
  final Color supportCautionMinor;

  /// The `supportCautionMajor` token.
  final Color supportCautionMajor;

  /// The `supportCautionUndefined` token.
  final Color supportCautionUndefined;

  /// The `focus` token.
  final Color focus;

  /// The `focusInset` token.
  final Color focusInset;

  /// The `focusInverse` token.
  final Color focusInverse;

  /// The `skeletonBackground` token.
  final Color skeletonBackground;

  /// The `skeletonElement` token.
  final Color skeletonElement;

  /// The `interactive` token.
  final Color interactive;

  /// The `highlight` token.
  final Color highlight;

  /// The `overlay` token.
  final Color overlay;

  /// The `toggleOff` token.
  final Color toggleOff;

  /// The `shadow` token.
  final Color shadow;

  /// The White theme.
  static final CarbonThemeData white = CarbonThemeData(
    brightness: Brightness.light,
    background: CarbonColors.white,
    backgroundInverse: CarbonColors.gray80,
    backgroundBrand: CarbonColors.blue60,
    backgroundActive: _alpha(CarbonColors.gray50, 0.5),
    backgroundHover: _alpha(CarbonColors.gray50, 0.12),
    backgroundInverseHover: CarbonColors.gray80Hover,
    backgroundSelected: _alpha(CarbonColors.gray50, 0.2),
    backgroundSelectedHover: _alpha(CarbonColors.gray50, 0.32),
    layer01: CarbonColors.gray10,
    layerActive01: CarbonColors.gray30,
    layerBackground01: CarbonColors.white,
    layerHover01: CarbonColors.gray10Hover,
    layerSelected01: CarbonColors.gray20,
    layerSelectedHover01: CarbonColors.gray20Hover,
    layer02: CarbonColors.white,
    layerActive02: CarbonColors.gray30,
    layerBackground02: CarbonColors.gray10,
    layerHover02: CarbonColors.whiteHover,
    layerSelected02: CarbonColors.gray20,
    layerSelectedHover02: CarbonColors.gray20Hover,
    layer03: CarbonColors.gray10,
    layerActive03: CarbonColors.gray30,
    layerBackground03: CarbonColors.white,
    layerHover03: CarbonColors.gray10Hover,
    layerSelected03: CarbonColors.gray20,
    layerSelectedHover03: CarbonColors.gray20Hover,
    layerSelectedInverse: CarbonColors.gray100,
    layerSelectedDisabled: CarbonColors.gray50,
    layerAccent01: CarbonColors.gray20,
    layerAccentActive01: CarbonColors.gray40,
    layerAccentHover01: CarbonColors.gray20Hover,
    layerAccent02: CarbonColors.gray20,
    layerAccentActive02: CarbonColors.gray40,
    layerAccentHover02: CarbonColors.gray20Hover,
    layerAccent03: CarbonColors.gray20,
    layerAccentActive03: CarbonColors.gray40,
    layerAccentHover03: CarbonColors.gray20Hover,
    field01: CarbonColors.gray10,
    fieldHover01: CarbonColors.gray10Hover,
    field02: CarbonColors.white,
    fieldHover02: CarbonColors.whiteHover,
    field03: CarbonColors.gray10,
    fieldHover03: CarbonColors.gray10Hover,
    borderSubtle00: CarbonColors.gray20,
    borderSubtle01: CarbonColors.gray30,
    borderSubtleSelected01: CarbonColors.gray30,
    borderSubtle02: CarbonColors.gray20,
    borderSubtleSelected02: CarbonColors.gray30,
    borderSubtle03: CarbonColors.gray30,
    borderSubtleSelected03: CarbonColors.gray30,
    borderStrong01: CarbonColors.gray50,
    borderStrong02: CarbonColors.gray50,
    borderStrong03: CarbonColors.gray50,
    borderTile01: CarbonColors.gray30,
    borderTile02: CarbonColors.gray40,
    borderTile03: CarbonColors.gray30,
    borderInverse: CarbonColors.gray100,
    borderInteractive: CarbonColors.blue60,
    borderDisabled: CarbonColors.gray30,
    textPrimary: CarbonColors.gray100,
    textSecondary: CarbonColors.gray70,
    textPlaceholder: _alpha(CarbonColors.gray100, 0.4),
    textHelper: CarbonColors.gray60,
    textError: CarbonColors.red60,
    textInverse: CarbonColors.white,
    textOnColor: CarbonColors.white,
    textOnColorDisabled: CarbonColors.gray50,
    textDisabled: _alpha(CarbonColors.gray100, 0.25),
    linkPrimary: CarbonColors.blue60,
    linkPrimaryHover: CarbonColors.blue70,
    linkSecondary: CarbonColors.blue70,
    linkInverse: CarbonColors.blue40,
    linkVisited: CarbonColors.purple60,
    linkInverseVisited: CarbonColors.purple40,
    linkInverseActive: CarbonColors.gray10,
    linkInverseHover: CarbonColors.blue30,
    iconPrimary: CarbonColors.gray100,
    iconSecondary: CarbonColors.gray70,
    iconInverse: CarbonColors.white,
    iconOnColor: CarbonColors.white,
    iconOnColorDisabled: CarbonColors.gray50,
    iconDisabled: _alpha(CarbonColors.gray100, 0.25),
    iconInteractive: CarbonColors.blue60,
    supportError: CarbonColors.red60,
    supportSuccess: CarbonColors.green50,
    supportWarning: CarbonColors.yellow30,
    supportInfo: CarbonColors.blue70,
    supportErrorInverse: CarbonColors.red50,
    supportSuccessInverse: CarbonColors.green40,
    supportWarningInverse: CarbonColors.yellow30,
    supportInfoInverse: CarbonColors.blue50,
    supportCautionMinor: CarbonColors.yellow30,
    supportCautionMajor: CarbonColors.orange40,
    supportCautionUndefined: CarbonColors.purple60,
    focus: CarbonColors.blue60,
    focusInset: CarbonColors.white,
    focusInverse: CarbonColors.white,
    skeletonBackground: CarbonColors.whiteHover,
    skeletonElement: CarbonColors.gray30,
    interactive: CarbonColors.blue60,
    highlight: CarbonColors.blue20,
    overlay: _alpha(CarbonColors.black, 0.6),
    toggleOff: CarbonColors.gray50,
    shadow: const Color.fromRGBO(0, 0, 0, 0.3),
  );

  /// The Gray 10 theme.
  static final CarbonThemeData gray10 = CarbonThemeData(
    brightness: Brightness.light,
    background: CarbonColors.gray10,
    backgroundInverse: CarbonColors.gray80,
    backgroundBrand: CarbonColors.blue60,
    backgroundActive: _alpha(CarbonColors.gray50, 0.5),
    backgroundHover: _alpha(CarbonColors.gray50, 0.12),
    backgroundInverseHover: CarbonColors.gray80Hover,
    backgroundSelected: _alpha(CarbonColors.gray50, 0.2),
    backgroundSelectedHover: _alpha(CarbonColors.gray50, 0.32),
    layer01: CarbonColors.white,
    layerActive01: CarbonColors.gray30,
    layerBackground01: CarbonColors.gray10,
    layerHover01: CarbonColors.whiteHover,
    layerSelected01: CarbonColors.gray20,
    layerSelectedHover01: CarbonColors.gray20Hover,
    layer02: CarbonColors.gray10,
    layerActive02: CarbonColors.gray30,
    layerBackground02: CarbonColors.white,
    layerHover02: CarbonColors.gray10Hover,
    layerSelected02: CarbonColors.gray20,
    layerSelectedHover02: CarbonColors.gray20Hover,
    layer03: CarbonColors.white,
    layerActive03: CarbonColors.gray30,
    layerBackground03: CarbonColors.gray10,
    layerHover03: CarbonColors.whiteHover,
    layerSelected03: CarbonColors.gray20,
    layerSelectedHover03: CarbonColors.gray20Hover,
    layerSelectedInverse: CarbonColors.gray100,
    layerSelectedDisabled: CarbonColors.gray50,
    layerAccent01: CarbonColors.gray20,
    layerAccentActive01: CarbonColors.gray40,
    layerAccentHover01: CarbonColors.gray20Hover,
    layerAccent02: CarbonColors.gray20,
    layerAccentActive02: CarbonColors.gray40,
    layerAccentHover02: CarbonColors.gray20Hover,
    layerAccent03: CarbonColors.gray20,
    layerAccentActive03: CarbonColors.gray40,
    layerAccentHover03: CarbonColors.gray20Hover,
    field01: CarbonColors.white,
    fieldHover01: CarbonColors.whiteHover,
    field02: CarbonColors.gray10,
    fieldHover02: CarbonColors.gray10Hover,
    field03: CarbonColors.white,
    fieldHover03: CarbonColors.whiteHover,
    borderSubtle00: CarbonColors.gray30,
    borderSubtle01: CarbonColors.gray20,
    borderSubtleSelected01: CarbonColors.gray30,
    borderSubtle02: CarbonColors.gray30,
    borderSubtleSelected02: CarbonColors.gray30,
    borderSubtle03: CarbonColors.gray20,
    borderSubtleSelected03: CarbonColors.gray30,
    borderStrong01: CarbonColors.gray50,
    borderStrong02: CarbonColors.gray50,
    borderStrong03: CarbonColors.gray50,
    borderTile01: CarbonColors.gray40,
    borderTile02: CarbonColors.gray30,
    borderTile03: CarbonColors.gray40,
    borderInverse: CarbonColors.gray100,
    borderInteractive: CarbonColors.blue60,
    borderDisabled: CarbonColors.gray30,
    textPrimary: CarbonColors.gray100,
    textSecondary: CarbonColors.gray70,
    textPlaceholder: _alpha(CarbonColors.gray100, 0.4),
    textHelper: CarbonColors.gray60,
    textError: CarbonColors.red60,
    textInverse: CarbonColors.white,
    textOnColor: CarbonColors.white,
    textOnColorDisabled: CarbonColors.gray50,
    textDisabled: _alpha(CarbonColors.gray100, 0.25),
    linkPrimary: CarbonColors.blue60,
    linkPrimaryHover: CarbonColors.blue70,
    linkSecondary: CarbonColors.blue70,
    linkInverse: CarbonColors.blue40,
    linkVisited: CarbonColors.purple60,
    linkInverseVisited: CarbonColors.purple40,
    linkInverseActive: CarbonColors.gray10,
    linkInverseHover: CarbonColors.blue30,
    iconPrimary: CarbonColors.gray100,
    iconSecondary: CarbonColors.gray70,
    iconInverse: CarbonColors.white,
    iconOnColor: CarbonColors.white,
    iconOnColorDisabled: CarbonColors.gray50,
    iconDisabled: _alpha(CarbonColors.gray100, 0.25),
    iconInteractive: CarbonColors.blue60,
    supportError: CarbonColors.red60,
    supportSuccess: CarbonColors.green50,
    supportWarning: CarbonColors.yellow30,
    supportInfo: CarbonColors.blue70,
    supportErrorInverse: CarbonColors.red50,
    supportSuccessInverse: CarbonColors.green40,
    supportWarningInverse: CarbonColors.yellow30,
    supportInfoInverse: CarbonColors.blue50,
    supportCautionMinor: CarbonColors.yellow30,
    supportCautionMajor: CarbonColors.orange40,
    supportCautionUndefined: CarbonColors.purple60,
    focus: CarbonColors.blue60,
    focusInset: CarbonColors.white,
    focusInverse: CarbonColors.white,
    skeletonBackground: CarbonColors.gray10Hover,
    skeletonElement: CarbonColors.gray30,
    interactive: CarbonColors.blue60,
    highlight: CarbonColors.blue20,
    overlay: _alpha(CarbonColors.black, 0.6),
    toggleOff: CarbonColors.gray50,
    shadow: const Color.fromRGBO(0, 0, 0, 0.3),
  );

  /// The Gray 90 theme.
  static final CarbonThemeData gray90 = CarbonThemeData(
    brightness: Brightness.dark,
    background: CarbonColors.gray90,
    backgroundInverse: CarbonColors.gray10,
    backgroundBrand: CarbonColors.blue60,
    backgroundActive: _alpha(CarbonColors.gray50, 0.4),
    backgroundHover: _alpha(CarbonColors.gray50, 0.16),
    backgroundInverseHover: CarbonColors.gray10Hover,
    backgroundSelected: _alpha(CarbonColors.gray50, 0.24),
    backgroundSelectedHover: _alpha(CarbonColors.gray50, 0.32),
    layer01: CarbonColors.gray80,
    layerActive01: CarbonColors.gray60,
    layerBackground01: CarbonColors.gray90,
    layerHover01: CarbonColors.gray80Hover,
    layerSelected01: CarbonColors.gray70,
    layerSelectedHover01: CarbonColors.gray70Hover,
    layer02: CarbonColors.gray70,
    layerActive02: CarbonColors.gray50,
    layerBackground02: CarbonColors.gray80,
    layerHover02: CarbonColors.gray70Hover,
    layerSelected02: CarbonColors.gray60,
    layerSelectedHover02: CarbonColors.gray60Hover,
    layer03: CarbonColors.gray60,
    layerActive03: CarbonColors.gray80,
    layerBackground03: CarbonColors.gray70,
    layerHover03: CarbonColors.gray60Hover,
    layerSelected03: CarbonColors.gray70,
    layerSelectedHover03: CarbonColors.gray70Hover,
    layerSelectedInverse: CarbonColors.gray10,
    layerSelectedDisabled: CarbonColors.gray40,
    layerAccent01: CarbonColors.gray70,
    layerAccentActive01: CarbonColors.gray50,
    layerAccentHover01: CarbonColors.gray70Hover,
    layerAccent02: CarbonColors.gray60,
    layerAccentActive02: CarbonColors.gray80,
    layerAccentHover02: CarbonColors.gray60Hover,
    layerAccent03: CarbonColors.gray50,
    layerAccentActive03: CarbonColors.gray70,
    layerAccentHover03: CarbonColors.gray50Hover,
    field01: CarbonColors.gray80,
    fieldHover01: CarbonColors.gray80Hover,
    field02: CarbonColors.gray70,
    fieldHover02: CarbonColors.gray70Hover,
    field03: CarbonColors.gray60,
    fieldHover03: CarbonColors.gray60Hover,
    borderSubtle00: CarbonColors.gray70,
    borderSubtle01: CarbonColors.gray60,
    borderSubtleSelected01: CarbonColors.gray50,
    borderSubtle02: CarbonColors.gray50,
    borderSubtleSelected02: CarbonColors.gray40,
    borderSubtle03: CarbonColors.gray50,
    borderSubtleSelected03: CarbonColors.gray40,
    borderStrong01: CarbonColors.gray50,
    borderStrong02: CarbonColors.gray40,
    borderStrong03: CarbonColors.gray30,
    borderTile01: CarbonColors.gray60,
    borderTile02: CarbonColors.gray50,
    borderTile03: CarbonColors.gray40,
    borderInverse: CarbonColors.gray10,
    borderInteractive: CarbonColors.blue50,
    borderDisabled: _alpha(CarbonColors.gray50, 0.5),
    textPrimary: CarbonColors.gray10,
    textSecondary: CarbonColors.gray30,
    textPlaceholder: _alpha(CarbonColors.gray10, 0.4),
    textHelper: CarbonColors.gray30,
    textError: CarbonColors.red30,
    textInverse: CarbonColors.gray100,
    textOnColor: CarbonColors.white,
    textOnColorDisabled: _alpha(CarbonColors.white, 0.25),
    textDisabled: _alpha(CarbonColors.gray10, 0.25),
    linkPrimary: CarbonColors.blue40,
    linkPrimaryHover: CarbonColors.blue30,
    linkSecondary: CarbonColors.blue30,
    linkInverse: CarbonColors.blue60,
    linkVisited: CarbonColors.purple40,
    linkInverseVisited: CarbonColors.purple60,
    linkInverseActive: CarbonColors.gray100,
    linkInverseHover: CarbonColors.blue70,
    iconPrimary: CarbonColors.gray10,
    iconSecondary: CarbonColors.gray30,
    iconInverse: CarbonColors.gray100,
    iconOnColor: CarbonColors.white,
    iconOnColorDisabled: _alpha(CarbonColors.white, 0.25),
    iconDisabled: _alpha(CarbonColors.gray10, 0.25),
    iconInteractive: CarbonColors.white,
    supportError: CarbonColors.red40,
    supportSuccess: CarbonColors.green40,
    supportWarning: CarbonColors.yellow30,
    supportInfo: CarbonColors.blue50,
    supportErrorInverse: CarbonColors.red60,
    supportSuccessInverse: CarbonColors.green50,
    supportWarningInverse: CarbonColors.yellow30,
    supportInfoInverse: CarbonColors.blue70,
    supportCautionMinor: CarbonColors.yellow30,
    supportCautionMajor: CarbonColors.orange40,
    supportCautionUndefined: CarbonColors.purple50,
    focus: CarbonColors.white,
    focusInset: CarbonColors.gray100,
    focusInverse: CarbonColors.blue60,
    skeletonBackground: CarbonColors.gray90Hover,
    skeletonElement: CarbonColors.gray70,
    interactive: CarbonColors.blue50,
    highlight: CarbonColors.blue80,
    overlay: _alpha(CarbonColors.black, 0.6),
    toggleOff: CarbonColors.gray50,
    shadow: _alpha(CarbonColors.black, 0.8),
  );

  /// The Gray 100 theme.
  static final CarbonThemeData gray100 = CarbonThemeData(
    brightness: Brightness.dark,
    background: CarbonColors.gray100,
    backgroundInverse: CarbonColors.gray10,
    backgroundBrand: CarbonColors.blue60,
    backgroundActive: _alpha(CarbonColors.gray50, 0.4),
    backgroundHover: _alpha(CarbonColors.gray50, 0.16),
    backgroundInverseHover: CarbonColors.gray10Hover,
    backgroundSelected: _alpha(CarbonColors.gray50, 0.24),
    backgroundSelectedHover: _alpha(CarbonColors.gray50, 0.32),
    layer01: CarbonColors.gray90,
    layerActive01: CarbonColors.gray70,
    layerBackground01: CarbonColors.gray100,
    layerHover01: CarbonColors.gray90Hover,
    layerSelected01: CarbonColors.gray80,
    layerSelectedHover01: CarbonColors.gray80Hover,
    layer02: CarbonColors.gray80,
    layerActive02: CarbonColors.gray60,
    layerBackground02: CarbonColors.gray90,
    layerHover02: CarbonColors.gray80Hover,
    layerSelected02: CarbonColors.gray70,
    layerSelectedHover02: CarbonColors.gray70Hover,
    layer03: CarbonColors.gray70,
    layerActive03: CarbonColors.gray50,
    layerBackground03: CarbonColors.gray80,
    layerHover03: CarbonColors.gray70Hover,
    layerSelected03: CarbonColors.gray60,
    layerSelectedHover03: CarbonColors.gray60Hover,
    layerSelectedInverse: CarbonColors.gray10,
    layerSelectedDisabled: CarbonColors.gray40,
    layerAccent01: CarbonColors.gray80,
    layerAccentActive01: CarbonColors.gray60,
    layerAccentHover01: CarbonColors.gray80Hover,
    layerAccent02: CarbonColors.gray70,
    layerAccentActive02: CarbonColors.gray50,
    layerAccentHover02: CarbonColors.gray70Hover,
    layerAccent03: CarbonColors.gray60,
    layerAccentActive03: CarbonColors.gray80,
    layerAccentHover03: CarbonColors.gray60Hover,
    field01: CarbonColors.gray90,
    fieldHover01: CarbonColors.gray90Hover,
    field02: CarbonColors.gray80,
    fieldHover02: CarbonColors.gray80Hover,
    field03: CarbonColors.gray70,
    fieldHover03: CarbonColors.gray70Hover,
    borderSubtle00: CarbonColors.gray80,
    borderSubtle01: CarbonColors.gray70,
    borderSubtleSelected01: CarbonColors.gray60,
    borderSubtle02: CarbonColors.gray60,
    borderSubtleSelected02: CarbonColors.gray50,
    borderSubtle03: CarbonColors.gray60,
    borderSubtleSelected03: CarbonColors.gray50,
    borderStrong01: CarbonColors.gray60,
    borderStrong02: CarbonColors.gray50,
    borderStrong03: CarbonColors.gray40,
    borderTile01: CarbonColors.gray70,
    borderTile02: CarbonColors.gray60,
    borderTile03: CarbonColors.gray50,
    borderInverse: CarbonColors.gray10,
    borderInteractive: CarbonColors.blue50,
    borderDisabled: _alpha(CarbonColors.gray50, 0.5),
    textPrimary: CarbonColors.gray10,
    textSecondary: CarbonColors.gray30,
    textPlaceholder: _alpha(CarbonColors.gray10, 0.4),
    textHelper: CarbonColors.gray40,
    textError: CarbonColors.red40,
    textInverse: CarbonColors.gray100,
    textOnColor: CarbonColors.white,
    textOnColorDisabled: _alpha(CarbonColors.white, 0.25),
    textDisabled: _alpha(CarbonColors.gray10, 0.25),
    linkPrimary: CarbonColors.blue40,
    linkPrimaryHover: CarbonColors.blue30,
    linkSecondary: CarbonColors.blue30,
    linkInverse: CarbonColors.blue60,
    linkVisited: CarbonColors.purple40,
    linkInverseVisited: CarbonColors.purple60,
    linkInverseActive: CarbonColors.gray100,
    linkInverseHover: CarbonColors.blue70,
    iconPrimary: CarbonColors.gray10,
    iconSecondary: CarbonColors.gray30,
    iconInverse: CarbonColors.gray100,
    iconOnColor: CarbonColors.white,
    iconOnColorDisabled: _alpha(CarbonColors.white, 0.25),
    iconDisabled: _alpha(CarbonColors.gray10, 0.25),
    iconInteractive: CarbonColors.white,
    supportError: CarbonColors.red50,
    supportSuccess: CarbonColors.green40,
    supportWarning: CarbonColors.yellow30,
    supportInfo: CarbonColors.blue50,
    supportErrorInverse: CarbonColors.red60,
    supportSuccessInverse: CarbonColors.green50,
    supportWarningInverse: CarbonColors.yellow30,
    supportInfoInverse: CarbonColors.blue70,
    supportCautionMinor: CarbonColors.yellow30,
    supportCautionMajor: CarbonColors.orange40,
    supportCautionUndefined: CarbonColors.purple50,
    focus: CarbonColors.white,
    focusInset: CarbonColors.gray100,
    focusInverse: CarbonColors.blue60,
    skeletonBackground: const Color(0xFF292929),
    skeletonElement: CarbonColors.gray80,
    interactive: CarbonColors.blue50,
    highlight: CarbonColors.blue90,
    overlay: _alpha(CarbonColors.black, 0.6),
    toggleOff: CarbonColors.gray60,
    shadow: _alpha(CarbonColors.black, 0.8),
  );

  /// A copy of this theme with the given tokens replaced.
  CarbonThemeData copyWith({
    Brightness? brightness,
    Color? background,
    Color? backgroundInverse,
    Color? backgroundBrand,
    Color? backgroundActive,
    Color? backgroundHover,
    Color? backgroundInverseHover,
    Color? backgroundSelected,
    Color? backgroundSelectedHover,
    Color? layer01,
    Color? layerActive01,
    Color? layerBackground01,
    Color? layerHover01,
    Color? layerSelected01,
    Color? layerSelectedHover01,
    Color? layer02,
    Color? layerActive02,
    Color? layerBackground02,
    Color? layerHover02,
    Color? layerSelected02,
    Color? layerSelectedHover02,
    Color? layer03,
    Color? layerActive03,
    Color? layerBackground03,
    Color? layerHover03,
    Color? layerSelected03,
    Color? layerSelectedHover03,
    Color? layerSelectedInverse,
    Color? layerSelectedDisabled,
    Color? layerAccent01,
    Color? layerAccentActive01,
    Color? layerAccentHover01,
    Color? layerAccent02,
    Color? layerAccentActive02,
    Color? layerAccentHover02,
    Color? layerAccent03,
    Color? layerAccentActive03,
    Color? layerAccentHover03,
    Color? field01,
    Color? fieldHover01,
    Color? field02,
    Color? fieldHover02,
    Color? field03,
    Color? fieldHover03,
    Color? borderSubtle00,
    Color? borderSubtle01,
    Color? borderSubtleSelected01,
    Color? borderSubtle02,
    Color? borderSubtleSelected02,
    Color? borderSubtle03,
    Color? borderSubtleSelected03,
    Color? borderStrong01,
    Color? borderStrong02,
    Color? borderStrong03,
    Color? borderTile01,
    Color? borderTile02,
    Color? borderTile03,
    Color? borderInverse,
    Color? borderInteractive,
    Color? borderDisabled,
    Color? textPrimary,
    Color? textSecondary,
    Color? textPlaceholder,
    Color? textHelper,
    Color? textError,
    Color? textInverse,
    Color? textOnColor,
    Color? textOnColorDisabled,
    Color? textDisabled,
    Color? linkPrimary,
    Color? linkPrimaryHover,
    Color? linkSecondary,
    Color? linkInverse,
    Color? linkVisited,
    Color? linkInverseVisited,
    Color? linkInverseActive,
    Color? linkInverseHover,
    Color? iconPrimary,
    Color? iconSecondary,
    Color? iconInverse,
    Color? iconOnColor,
    Color? iconOnColorDisabled,
    Color? iconDisabled,
    Color? iconInteractive,
    Color? supportError,
    Color? supportSuccess,
    Color? supportWarning,
    Color? supportInfo,
    Color? supportErrorInverse,
    Color? supportSuccessInverse,
    Color? supportWarningInverse,
    Color? supportInfoInverse,
    Color? supportCautionMinor,
    Color? supportCautionMajor,
    Color? supportCautionUndefined,
    Color? focus,
    Color? focusInset,
    Color? focusInverse,
    Color? skeletonBackground,
    Color? skeletonElement,
    Color? interactive,
    Color? highlight,
    Color? overlay,
    Color? toggleOff,
    Color? shadow,
  }) {
    return CarbonThemeData(
      brightness: brightness ?? this.brightness,
      background: background ?? this.background,
      backgroundInverse: backgroundInverse ?? this.backgroundInverse,
      backgroundBrand: backgroundBrand ?? this.backgroundBrand,
      backgroundActive: backgroundActive ?? this.backgroundActive,
      backgroundHover: backgroundHover ?? this.backgroundHover,
      backgroundInverseHover:
          backgroundInverseHover ?? this.backgroundInverseHover,
      backgroundSelected: backgroundSelected ?? this.backgroundSelected,
      backgroundSelectedHover:
          backgroundSelectedHover ?? this.backgroundSelectedHover,
      layer01: layer01 ?? this.layer01,
      layerActive01: layerActive01 ?? this.layerActive01,
      layerBackground01: layerBackground01 ?? this.layerBackground01,
      layerHover01: layerHover01 ?? this.layerHover01,
      layerSelected01: layerSelected01 ?? this.layerSelected01,
      layerSelectedHover01: layerSelectedHover01 ?? this.layerSelectedHover01,
      layer02: layer02 ?? this.layer02,
      layerActive02: layerActive02 ?? this.layerActive02,
      layerBackground02: layerBackground02 ?? this.layerBackground02,
      layerHover02: layerHover02 ?? this.layerHover02,
      layerSelected02: layerSelected02 ?? this.layerSelected02,
      layerSelectedHover02: layerSelectedHover02 ?? this.layerSelectedHover02,
      layer03: layer03 ?? this.layer03,
      layerActive03: layerActive03 ?? this.layerActive03,
      layerBackground03: layerBackground03 ?? this.layerBackground03,
      layerHover03: layerHover03 ?? this.layerHover03,
      layerSelected03: layerSelected03 ?? this.layerSelected03,
      layerSelectedHover03: layerSelectedHover03 ?? this.layerSelectedHover03,
      layerSelectedInverse: layerSelectedInverse ?? this.layerSelectedInverse,
      layerSelectedDisabled:
          layerSelectedDisabled ?? this.layerSelectedDisabled,
      layerAccent01: layerAccent01 ?? this.layerAccent01,
      layerAccentActive01: layerAccentActive01 ?? this.layerAccentActive01,
      layerAccentHover01: layerAccentHover01 ?? this.layerAccentHover01,
      layerAccent02: layerAccent02 ?? this.layerAccent02,
      layerAccentActive02: layerAccentActive02 ?? this.layerAccentActive02,
      layerAccentHover02: layerAccentHover02 ?? this.layerAccentHover02,
      layerAccent03: layerAccent03 ?? this.layerAccent03,
      layerAccentActive03: layerAccentActive03 ?? this.layerAccentActive03,
      layerAccentHover03: layerAccentHover03 ?? this.layerAccentHover03,
      field01: field01 ?? this.field01,
      fieldHover01: fieldHover01 ?? this.fieldHover01,
      field02: field02 ?? this.field02,
      fieldHover02: fieldHover02 ?? this.fieldHover02,
      field03: field03 ?? this.field03,
      fieldHover03: fieldHover03 ?? this.fieldHover03,
      borderSubtle00: borderSubtle00 ?? this.borderSubtle00,
      borderSubtle01: borderSubtle01 ?? this.borderSubtle01,
      borderSubtleSelected01:
          borderSubtleSelected01 ?? this.borderSubtleSelected01,
      borderSubtle02: borderSubtle02 ?? this.borderSubtle02,
      borderSubtleSelected02:
          borderSubtleSelected02 ?? this.borderSubtleSelected02,
      borderSubtle03: borderSubtle03 ?? this.borderSubtle03,
      borderSubtleSelected03:
          borderSubtleSelected03 ?? this.borderSubtleSelected03,
      borderStrong01: borderStrong01 ?? this.borderStrong01,
      borderStrong02: borderStrong02 ?? this.borderStrong02,
      borderStrong03: borderStrong03 ?? this.borderStrong03,
      borderTile01: borderTile01 ?? this.borderTile01,
      borderTile02: borderTile02 ?? this.borderTile02,
      borderTile03: borderTile03 ?? this.borderTile03,
      borderInverse: borderInverse ?? this.borderInverse,
      borderInteractive: borderInteractive ?? this.borderInteractive,
      borderDisabled: borderDisabled ?? this.borderDisabled,
      textPrimary: textPrimary ?? this.textPrimary,
      textSecondary: textSecondary ?? this.textSecondary,
      textPlaceholder: textPlaceholder ?? this.textPlaceholder,
      textHelper: textHelper ?? this.textHelper,
      textError: textError ?? this.textError,
      textInverse: textInverse ?? this.textInverse,
      textOnColor: textOnColor ?? this.textOnColor,
      textOnColorDisabled: textOnColorDisabled ?? this.textOnColorDisabled,
      textDisabled: textDisabled ?? this.textDisabled,
      linkPrimary: linkPrimary ?? this.linkPrimary,
      linkPrimaryHover: linkPrimaryHover ?? this.linkPrimaryHover,
      linkSecondary: linkSecondary ?? this.linkSecondary,
      linkInverse: linkInverse ?? this.linkInverse,
      linkVisited: linkVisited ?? this.linkVisited,
      linkInverseVisited: linkInverseVisited ?? this.linkInverseVisited,
      linkInverseActive: linkInverseActive ?? this.linkInverseActive,
      linkInverseHover: linkInverseHover ?? this.linkInverseHover,
      iconPrimary: iconPrimary ?? this.iconPrimary,
      iconSecondary: iconSecondary ?? this.iconSecondary,
      iconInverse: iconInverse ?? this.iconInverse,
      iconOnColor: iconOnColor ?? this.iconOnColor,
      iconOnColorDisabled: iconOnColorDisabled ?? this.iconOnColorDisabled,
      iconDisabled: iconDisabled ?? this.iconDisabled,
      iconInteractive: iconInteractive ?? this.iconInteractive,
      supportError: supportError ?? this.supportError,
      supportSuccess: supportSuccess ?? this.supportSuccess,
      supportWarning: supportWarning ?? this.supportWarning,
      supportInfo: supportInfo ?? this.supportInfo,
      supportErrorInverse: supportErrorInverse ?? this.supportErrorInverse,
      supportSuccessInverse:
          supportSuccessInverse ?? this.supportSuccessInverse,
      supportWarningInverse:
          supportWarningInverse ?? this.supportWarningInverse,
      supportInfoInverse: supportInfoInverse ?? this.supportInfoInverse,
      supportCautionMinor: supportCautionMinor ?? this.supportCautionMinor,
      supportCautionMajor: supportCautionMajor ?? this.supportCautionMajor,
      supportCautionUndefined:
          supportCautionUndefined ?? this.supportCautionUndefined,
      focus: focus ?? this.focus,
      focusInset: focusInset ?? this.focusInset,
      focusInverse: focusInverse ?? this.focusInverse,
      skeletonBackground: skeletonBackground ?? this.skeletonBackground,
      skeletonElement: skeletonElement ?? this.skeletonElement,
      interactive: interactive ?? this.interactive,
      highlight: highlight ?? this.highlight,
      overlay: overlay ?? this.overlay,
      toggleOff: toggleOff ?? this.toggleOff,
      shadow: shadow ?? this.shadow,
    );
  }

  /// Linearly interpolates between themes [a] and [b].
  ///
  /// [brightness] snaps to [b] from the midpoint.
  static CarbonThemeData lerp(CarbonThemeData a, CarbonThemeData b, double t) {
    return CarbonThemeData(
      brightness: t < 0.5 ? a.brightness : b.brightness,
      background: Color.lerp(a.background, b.background, t)!,
      backgroundInverse: Color.lerp(
        a.backgroundInverse,
        b.backgroundInverse,
        t,
      )!,
      backgroundBrand: Color.lerp(a.backgroundBrand, b.backgroundBrand, t)!,
      backgroundActive: Color.lerp(a.backgroundActive, b.backgroundActive, t)!,
      backgroundHover: Color.lerp(a.backgroundHover, b.backgroundHover, t)!,
      backgroundInverseHover: Color.lerp(
        a.backgroundInverseHover,
        b.backgroundInverseHover,
        t,
      )!,
      backgroundSelected: Color.lerp(
        a.backgroundSelected,
        b.backgroundSelected,
        t,
      )!,
      backgroundSelectedHover: Color.lerp(
        a.backgroundSelectedHover,
        b.backgroundSelectedHover,
        t,
      )!,
      layer01: Color.lerp(a.layer01, b.layer01, t)!,
      layerActive01: Color.lerp(a.layerActive01, b.layerActive01, t)!,
      layerBackground01: Color.lerp(
        a.layerBackground01,
        b.layerBackground01,
        t,
      )!,
      layerHover01: Color.lerp(a.layerHover01, b.layerHover01, t)!,
      layerSelected01: Color.lerp(a.layerSelected01, b.layerSelected01, t)!,
      layerSelectedHover01: Color.lerp(
        a.layerSelectedHover01,
        b.layerSelectedHover01,
        t,
      )!,
      layer02: Color.lerp(a.layer02, b.layer02, t)!,
      layerActive02: Color.lerp(a.layerActive02, b.layerActive02, t)!,
      layerBackground02: Color.lerp(
        a.layerBackground02,
        b.layerBackground02,
        t,
      )!,
      layerHover02: Color.lerp(a.layerHover02, b.layerHover02, t)!,
      layerSelected02: Color.lerp(a.layerSelected02, b.layerSelected02, t)!,
      layerSelectedHover02: Color.lerp(
        a.layerSelectedHover02,
        b.layerSelectedHover02,
        t,
      )!,
      layer03: Color.lerp(a.layer03, b.layer03, t)!,
      layerActive03: Color.lerp(a.layerActive03, b.layerActive03, t)!,
      layerBackground03: Color.lerp(
        a.layerBackground03,
        b.layerBackground03,
        t,
      )!,
      layerHover03: Color.lerp(a.layerHover03, b.layerHover03, t)!,
      layerSelected03: Color.lerp(a.layerSelected03, b.layerSelected03, t)!,
      layerSelectedHover03: Color.lerp(
        a.layerSelectedHover03,
        b.layerSelectedHover03,
        t,
      )!,
      layerSelectedInverse: Color.lerp(
        a.layerSelectedInverse,
        b.layerSelectedInverse,
        t,
      )!,
      layerSelectedDisabled: Color.lerp(
        a.layerSelectedDisabled,
        b.layerSelectedDisabled,
        t,
      )!,
      layerAccent01: Color.lerp(a.layerAccent01, b.layerAccent01, t)!,
      layerAccentActive01: Color.lerp(
        a.layerAccentActive01,
        b.layerAccentActive01,
        t,
      )!,
      layerAccentHover01: Color.lerp(
        a.layerAccentHover01,
        b.layerAccentHover01,
        t,
      )!,
      layerAccent02: Color.lerp(a.layerAccent02, b.layerAccent02, t)!,
      layerAccentActive02: Color.lerp(
        a.layerAccentActive02,
        b.layerAccentActive02,
        t,
      )!,
      layerAccentHover02: Color.lerp(
        a.layerAccentHover02,
        b.layerAccentHover02,
        t,
      )!,
      layerAccent03: Color.lerp(a.layerAccent03, b.layerAccent03, t)!,
      layerAccentActive03: Color.lerp(
        a.layerAccentActive03,
        b.layerAccentActive03,
        t,
      )!,
      layerAccentHover03: Color.lerp(
        a.layerAccentHover03,
        b.layerAccentHover03,
        t,
      )!,
      field01: Color.lerp(a.field01, b.field01, t)!,
      fieldHover01: Color.lerp(a.fieldHover01, b.fieldHover01, t)!,
      field02: Color.lerp(a.field02, b.field02, t)!,
      fieldHover02: Color.lerp(a.fieldHover02, b.fieldHover02, t)!,
      field03: Color.lerp(a.field03, b.field03, t)!,
      fieldHover03: Color.lerp(a.fieldHover03, b.fieldHover03, t)!,
      borderSubtle00: Color.lerp(a.borderSubtle00, b.borderSubtle00, t)!,
      borderSubtle01: Color.lerp(a.borderSubtle01, b.borderSubtle01, t)!,
      borderSubtleSelected01: Color.lerp(
        a.borderSubtleSelected01,
        b.borderSubtleSelected01,
        t,
      )!,
      borderSubtle02: Color.lerp(a.borderSubtle02, b.borderSubtle02, t)!,
      borderSubtleSelected02: Color.lerp(
        a.borderSubtleSelected02,
        b.borderSubtleSelected02,
        t,
      )!,
      borderSubtle03: Color.lerp(a.borderSubtle03, b.borderSubtle03, t)!,
      borderSubtleSelected03: Color.lerp(
        a.borderSubtleSelected03,
        b.borderSubtleSelected03,
        t,
      )!,
      borderStrong01: Color.lerp(a.borderStrong01, b.borderStrong01, t)!,
      borderStrong02: Color.lerp(a.borderStrong02, b.borderStrong02, t)!,
      borderStrong03: Color.lerp(a.borderStrong03, b.borderStrong03, t)!,
      borderTile01: Color.lerp(a.borderTile01, b.borderTile01, t)!,
      borderTile02: Color.lerp(a.borderTile02, b.borderTile02, t)!,
      borderTile03: Color.lerp(a.borderTile03, b.borderTile03, t)!,
      borderInverse: Color.lerp(a.borderInverse, b.borderInverse, t)!,
      borderInteractive: Color.lerp(
        a.borderInteractive,
        b.borderInteractive,
        t,
      )!,
      borderDisabled: Color.lerp(a.borderDisabled, b.borderDisabled, t)!,
      textPrimary: Color.lerp(a.textPrimary, b.textPrimary, t)!,
      textSecondary: Color.lerp(a.textSecondary, b.textSecondary, t)!,
      textPlaceholder: Color.lerp(a.textPlaceholder, b.textPlaceholder, t)!,
      textHelper: Color.lerp(a.textHelper, b.textHelper, t)!,
      textError: Color.lerp(a.textError, b.textError, t)!,
      textInverse: Color.lerp(a.textInverse, b.textInverse, t)!,
      textOnColor: Color.lerp(a.textOnColor, b.textOnColor, t)!,
      textOnColorDisabled: Color.lerp(
        a.textOnColorDisabled,
        b.textOnColorDisabled,
        t,
      )!,
      textDisabled: Color.lerp(a.textDisabled, b.textDisabled, t)!,
      linkPrimary: Color.lerp(a.linkPrimary, b.linkPrimary, t)!,
      linkPrimaryHover: Color.lerp(a.linkPrimaryHover, b.linkPrimaryHover, t)!,
      linkSecondary: Color.lerp(a.linkSecondary, b.linkSecondary, t)!,
      linkInverse: Color.lerp(a.linkInverse, b.linkInverse, t)!,
      linkVisited: Color.lerp(a.linkVisited, b.linkVisited, t)!,
      linkInverseVisited: Color.lerp(
        a.linkInverseVisited,
        b.linkInverseVisited,
        t,
      )!,
      linkInverseActive: Color.lerp(
        a.linkInverseActive,
        b.linkInverseActive,
        t,
      )!,
      linkInverseHover: Color.lerp(a.linkInverseHover, b.linkInverseHover, t)!,
      iconPrimary: Color.lerp(a.iconPrimary, b.iconPrimary, t)!,
      iconSecondary: Color.lerp(a.iconSecondary, b.iconSecondary, t)!,
      iconInverse: Color.lerp(a.iconInverse, b.iconInverse, t)!,
      iconOnColor: Color.lerp(a.iconOnColor, b.iconOnColor, t)!,
      iconOnColorDisabled: Color.lerp(
        a.iconOnColorDisabled,
        b.iconOnColorDisabled,
        t,
      )!,
      iconDisabled: Color.lerp(a.iconDisabled, b.iconDisabled, t)!,
      iconInteractive: Color.lerp(a.iconInteractive, b.iconInteractive, t)!,
      supportError: Color.lerp(a.supportError, b.supportError, t)!,
      supportSuccess: Color.lerp(a.supportSuccess, b.supportSuccess, t)!,
      supportWarning: Color.lerp(a.supportWarning, b.supportWarning, t)!,
      supportInfo: Color.lerp(a.supportInfo, b.supportInfo, t)!,
      supportErrorInverse: Color.lerp(
        a.supportErrorInverse,
        b.supportErrorInverse,
        t,
      )!,
      supportSuccessInverse: Color.lerp(
        a.supportSuccessInverse,
        b.supportSuccessInverse,
        t,
      )!,
      supportWarningInverse: Color.lerp(
        a.supportWarningInverse,
        b.supportWarningInverse,
        t,
      )!,
      supportInfoInverse: Color.lerp(
        a.supportInfoInverse,
        b.supportInfoInverse,
        t,
      )!,
      supportCautionMinor: Color.lerp(
        a.supportCautionMinor,
        b.supportCautionMinor,
        t,
      )!,
      supportCautionMajor: Color.lerp(
        a.supportCautionMajor,
        b.supportCautionMajor,
        t,
      )!,
      supportCautionUndefined: Color.lerp(
        a.supportCautionUndefined,
        b.supportCautionUndefined,
        t,
      )!,
      focus: Color.lerp(a.focus, b.focus, t)!,
      focusInset: Color.lerp(a.focusInset, b.focusInset, t)!,
      focusInverse: Color.lerp(a.focusInverse, b.focusInverse, t)!,
      skeletonBackground: Color.lerp(
        a.skeletonBackground,
        b.skeletonBackground,
        t,
      )!,
      skeletonElement: Color.lerp(a.skeletonElement, b.skeletonElement, t)!,
      interactive: Color.lerp(a.interactive, b.interactive, t)!,
      highlight: Color.lerp(a.highlight, b.highlight, t)!,
      overlay: Color.lerp(a.overlay, b.overlay, t)!,
      toggleOff: Color.lerp(a.toggleOff, b.toggleOff, t)!,
      shadow: Color.lerp(a.shadow, b.shadow, t)!,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is CarbonThemeData &&
        other.brightness == brightness &&
        other.background == background &&
        other.backgroundInverse == backgroundInverse &&
        other.backgroundBrand == backgroundBrand &&
        other.backgroundActive == backgroundActive &&
        other.backgroundHover == backgroundHover &&
        other.backgroundInverseHover == backgroundInverseHover &&
        other.backgroundSelected == backgroundSelected &&
        other.backgroundSelectedHover == backgroundSelectedHover &&
        other.layer01 == layer01 &&
        other.layerActive01 == layerActive01 &&
        other.layerBackground01 == layerBackground01 &&
        other.layerHover01 == layerHover01 &&
        other.layerSelected01 == layerSelected01 &&
        other.layerSelectedHover01 == layerSelectedHover01 &&
        other.layer02 == layer02 &&
        other.layerActive02 == layerActive02 &&
        other.layerBackground02 == layerBackground02 &&
        other.layerHover02 == layerHover02 &&
        other.layerSelected02 == layerSelected02 &&
        other.layerSelectedHover02 == layerSelectedHover02 &&
        other.layer03 == layer03 &&
        other.layerActive03 == layerActive03 &&
        other.layerBackground03 == layerBackground03 &&
        other.layerHover03 == layerHover03 &&
        other.layerSelected03 == layerSelected03 &&
        other.layerSelectedHover03 == layerSelectedHover03 &&
        other.layerSelectedInverse == layerSelectedInverse &&
        other.layerSelectedDisabled == layerSelectedDisabled &&
        other.layerAccent01 == layerAccent01 &&
        other.layerAccentActive01 == layerAccentActive01 &&
        other.layerAccentHover01 == layerAccentHover01 &&
        other.layerAccent02 == layerAccent02 &&
        other.layerAccentActive02 == layerAccentActive02 &&
        other.layerAccentHover02 == layerAccentHover02 &&
        other.layerAccent03 == layerAccent03 &&
        other.layerAccentActive03 == layerAccentActive03 &&
        other.layerAccentHover03 == layerAccentHover03 &&
        other.field01 == field01 &&
        other.fieldHover01 == fieldHover01 &&
        other.field02 == field02 &&
        other.fieldHover02 == fieldHover02 &&
        other.field03 == field03 &&
        other.fieldHover03 == fieldHover03 &&
        other.borderSubtle00 == borderSubtle00 &&
        other.borderSubtle01 == borderSubtle01 &&
        other.borderSubtleSelected01 == borderSubtleSelected01 &&
        other.borderSubtle02 == borderSubtle02 &&
        other.borderSubtleSelected02 == borderSubtleSelected02 &&
        other.borderSubtle03 == borderSubtle03 &&
        other.borderSubtleSelected03 == borderSubtleSelected03 &&
        other.borderStrong01 == borderStrong01 &&
        other.borderStrong02 == borderStrong02 &&
        other.borderStrong03 == borderStrong03 &&
        other.borderTile01 == borderTile01 &&
        other.borderTile02 == borderTile02 &&
        other.borderTile03 == borderTile03 &&
        other.borderInverse == borderInverse &&
        other.borderInteractive == borderInteractive &&
        other.borderDisabled == borderDisabled &&
        other.textPrimary == textPrimary &&
        other.textSecondary == textSecondary &&
        other.textPlaceholder == textPlaceholder &&
        other.textHelper == textHelper &&
        other.textError == textError &&
        other.textInverse == textInverse &&
        other.textOnColor == textOnColor &&
        other.textOnColorDisabled == textOnColorDisabled &&
        other.textDisabled == textDisabled &&
        other.linkPrimary == linkPrimary &&
        other.linkPrimaryHover == linkPrimaryHover &&
        other.linkSecondary == linkSecondary &&
        other.linkInverse == linkInverse &&
        other.linkVisited == linkVisited &&
        other.linkInverseVisited == linkInverseVisited &&
        other.linkInverseActive == linkInverseActive &&
        other.linkInverseHover == linkInverseHover &&
        other.iconPrimary == iconPrimary &&
        other.iconSecondary == iconSecondary &&
        other.iconInverse == iconInverse &&
        other.iconOnColor == iconOnColor &&
        other.iconOnColorDisabled == iconOnColorDisabled &&
        other.iconDisabled == iconDisabled &&
        other.iconInteractive == iconInteractive &&
        other.supportError == supportError &&
        other.supportSuccess == supportSuccess &&
        other.supportWarning == supportWarning &&
        other.supportInfo == supportInfo &&
        other.supportErrorInverse == supportErrorInverse &&
        other.supportSuccessInverse == supportSuccessInverse &&
        other.supportWarningInverse == supportWarningInverse &&
        other.supportInfoInverse == supportInfoInverse &&
        other.supportCautionMinor == supportCautionMinor &&
        other.supportCautionMajor == supportCautionMajor &&
        other.supportCautionUndefined == supportCautionUndefined &&
        other.focus == focus &&
        other.focusInset == focusInset &&
        other.focusInverse == focusInverse &&
        other.skeletonBackground == skeletonBackground &&
        other.skeletonElement == skeletonElement &&
        other.interactive == interactive &&
        other.highlight == highlight &&
        other.overlay == overlay &&
        other.toggleOff == toggleOff &&
        other.shadow == shadow;
  }

  @override
  int get hashCode => Object.hashAll(<Object?>[
    brightness,
    background,
    backgroundInverse,
    backgroundBrand,
    backgroundActive,
    backgroundHover,
    backgroundInverseHover,
    backgroundSelected,
    backgroundSelectedHover,
    layer01,
    layerActive01,
    layerBackground01,
    layerHover01,
    layerSelected01,
    layerSelectedHover01,
    layer02,
    layerActive02,
    layerBackground02,
    layerHover02,
    layerSelected02,
    layerSelectedHover02,
    layer03,
    layerActive03,
    layerBackground03,
    layerHover03,
    layerSelected03,
    layerSelectedHover03,
    layerSelectedInverse,
    layerSelectedDisabled,
    layerAccent01,
    layerAccentActive01,
    layerAccentHover01,
    layerAccent02,
    layerAccentActive02,
    layerAccentHover02,
    layerAccent03,
    layerAccentActive03,
    layerAccentHover03,
    field01,
    fieldHover01,
    field02,
    fieldHover02,
    field03,
    fieldHover03,
    borderSubtle00,
    borderSubtle01,
    borderSubtleSelected01,
    borderSubtle02,
    borderSubtleSelected02,
    borderSubtle03,
    borderSubtleSelected03,
    borderStrong01,
    borderStrong02,
    borderStrong03,
    borderTile01,
    borderTile02,
    borderTile03,
    borderInverse,
    borderInteractive,
    borderDisabled,
    textPrimary,
    textSecondary,
    textPlaceholder,
    textHelper,
    textError,
    textInverse,
    textOnColor,
    textOnColorDisabled,
    textDisabled,
    linkPrimary,
    linkPrimaryHover,
    linkSecondary,
    linkInverse,
    linkVisited,
    linkInverseVisited,
    linkInverseActive,
    linkInverseHover,
    iconPrimary,
    iconSecondary,
    iconInverse,
    iconOnColor,
    iconOnColorDisabled,
    iconDisabled,
    iconInteractive,
    supportError,
    supportSuccess,
    supportWarning,
    supportInfo,
    supportErrorInverse,
    supportSuccessInverse,
    supportWarningInverse,
    supportInfoInverse,
    supportCautionMinor,
    supportCautionMajor,
    supportCautionUndefined,
    focus,
    focusInset,
    focusInverse,
    skeletonBackground,
    skeletonElement,
    interactive,
    highlight,
    overlay,
    toggleOff,
    shadow,
  ]);
}

Color _alpha(Color color, double opacity) => color.withValues(alpha: opacity);
