// Copyright 2026 Bizjak Tech OÜ
//
// This file is part of Carbide and is licensed under the GNU Affero General
// Public License v3.0 or later. See the LICENSE file in the project root.
//
// GENERATED by tool/generate_carbon_themes.py — do not edit by hand.
//
// Semantic token values are ported verbatim from the Apache-2.0 licensed Carbon
// Design System (@carbon/themes). See the NOTICE file for attribution.

import 'dart:ui' show Brightness, Color;

import 'package:flutter/foundation.dart' show immutable;

import '../foundations/colors.dart';

/// The resolved semantic color tokens for one Carbon theme.
///
/// Carbon ships four themes — [white], [gray10], [gray90], and
/// [gray100] — each mapping the same set of semantic tokens
/// (background, layer, field, text, support, …) onto the palette. Use
/// a built-in, or construct a custom theme with the constructor.
@immutable
class CarbonThemeData {
  /// Creates a theme from an explicit set of semantic tokens.
  const CarbonThemeData({
    required this.brightness,
    required this.background,
    required this.backgroundInverse,
    required this.backgroundBrand,
    required this.backgroundActive,
    required this.backgroundHover,
    required this.backgroundInverseHover,
    required this.backgroundSelected,
    required this.backgroundSelectedHover,
    required this.layer01,
    required this.layerActive01,
    required this.layerBackground01,
    required this.layerHover01,
    required this.layerSelected01,
    required this.layerSelectedHover01,
    required this.layer02,
    required this.layerActive02,
    required this.layerBackground02,
    required this.layerHover02,
    required this.layerSelected02,
    required this.layerSelectedHover02,
    required this.layer03,
    required this.layerActive03,
    required this.layerBackground03,
    required this.layerHover03,
    required this.layerSelected03,
    required this.layerSelectedHover03,
    required this.layerSelectedInverse,
    required this.layerSelectedDisabled,
    required this.layerAccent01,
    required this.layerAccentActive01,
    required this.layerAccentHover01,
    required this.layerAccent02,
    required this.layerAccentActive02,
    required this.layerAccentHover02,
    required this.layerAccent03,
    required this.layerAccentActive03,
    required this.layerAccentHover03,
    required this.field01,
    required this.fieldHover01,
    required this.field02,
    required this.fieldHover02,
    required this.field03,
    required this.fieldHover03,
    required this.borderSubtle00,
    required this.borderSubtle01,
    required this.borderSubtleSelected01,
    required this.borderSubtle02,
    required this.borderSubtleSelected02,
    required this.borderSubtle03,
    required this.borderSubtleSelected03,
    required this.borderStrong01,
    required this.borderStrong02,
    required this.borderStrong03,
    required this.borderTile01,
    required this.borderTile02,
    required this.borderTile03,
    required this.borderInverse,
    required this.borderInteractive,
    required this.borderDisabled,
    required this.textPrimary,
    required this.textSecondary,
    required this.textPlaceholder,
    required this.textHelper,
    required this.textError,
    required this.textInverse,
    required this.textOnColor,
    required this.textOnColorDisabled,
    required this.textDisabled,
    required this.linkPrimary,
    required this.linkPrimaryHover,
    required this.linkSecondary,
    required this.linkInverse,
    required this.linkVisited,
    required this.linkInverseVisited,
    required this.linkInverseActive,
    required this.linkInverseHover,
    required this.iconPrimary,
    required this.iconSecondary,
    required this.iconInverse,
    required this.iconOnColor,
    required this.iconOnColorDisabled,
    required this.iconDisabled,
    required this.iconInteractive,
    required this.supportError,
    required this.supportSuccess,
    required this.supportWarning,
    required this.supportInfo,
    required this.supportErrorInverse,
    required this.supportSuccessInverse,
    required this.supportWarningInverse,
    required this.supportInfoInverse,
    required this.supportCautionMinor,
    required this.supportCautionMajor,
    required this.supportCautionUndefined,
    required this.focus,
    required this.focusInset,
    required this.focusInverse,
    required this.skeletonBackground,
    required this.skeletonElement,
    required this.interactive,
    required this.highlight,
    required this.overlay,
    required this.toggleOff,
    required this.shadow,
  });

  /// Whether this is a light or dark theme.
  final Brightness brightness;

  /// The `background` token.
  final Color background;

  /// The `backgroundInverse` token.
  final Color backgroundInverse;

  /// The `backgroundBrand` token.
  final Color backgroundBrand;

  /// The `backgroundActive` token.
  final Color backgroundActive;

  /// The `backgroundHover` token.
  final Color backgroundHover;

  /// The `backgroundInverseHover` token.
  final Color backgroundInverseHover;

  /// The `backgroundSelected` token.
  final Color backgroundSelected;

  /// The `backgroundSelectedHover` token.
  final Color backgroundSelectedHover;

  /// The `layer01` token.
  final Color layer01;

  /// The `layerActive01` token.
  final Color layerActive01;

  /// The `layerBackground01` token.
  final Color layerBackground01;

  /// The `layerHover01` token.
  final Color layerHover01;

  /// The `layerSelected01` token.
  final Color layerSelected01;

  /// The `layerSelectedHover01` token.
  final Color layerSelectedHover01;

  /// The `layer02` token.
  final Color layer02;

  /// The `layerActive02` token.
  final Color layerActive02;

  /// The `layerBackground02` token.
  final Color layerBackground02;

  /// The `layerHover02` token.
  final Color layerHover02;

  /// The `layerSelected02` token.
  final Color layerSelected02;

  /// The `layerSelectedHover02` token.
  final Color layerSelectedHover02;

  /// The `layer03` token.
  final Color layer03;

  /// The `layerActive03` token.
  final Color layerActive03;

  /// The `layerBackground03` token.
  final Color layerBackground03;

  /// The `layerHover03` token.
  final Color layerHover03;

  /// The `layerSelected03` token.
  final Color layerSelected03;

  /// The `layerSelectedHover03` token.
  final Color layerSelectedHover03;

  /// The `layerSelectedInverse` token.
  final Color layerSelectedInverse;

  /// The `layerSelectedDisabled` token.
  final Color layerSelectedDisabled;

  /// The `layerAccent01` token.
  final Color layerAccent01;

  /// The `layerAccentActive01` token.
  final Color layerAccentActive01;

  /// The `layerAccentHover01` token.
  final Color layerAccentHover01;

  /// The `layerAccent02` token.
  final Color layerAccent02;

  /// The `layerAccentActive02` token.
  final Color layerAccentActive02;

  /// The `layerAccentHover02` token.
  final Color layerAccentHover02;

  /// The `layerAccent03` token.
  final Color layerAccent03;

  /// The `layerAccentActive03` token.
  final Color layerAccentActive03;

  /// The `layerAccentHover03` token.
  final Color layerAccentHover03;

  /// The `field01` token.
  final Color field01;

  /// The `fieldHover01` token.
  final Color fieldHover01;

  /// The `field02` token.
  final Color field02;

  /// The `fieldHover02` token.
  final Color fieldHover02;

  /// The `field03` token.
  final Color field03;

  /// The `fieldHover03` token.
  final Color fieldHover03;

  /// The `borderSubtle00` token.
  final Color borderSubtle00;

  /// The `borderSubtle01` token.
  final Color borderSubtle01;

  /// The `borderSubtleSelected01` token.
  final Color borderSubtleSelected01;

  /// The `borderSubtle02` token.
  final Color borderSubtle02;

  /// The `borderSubtleSelected02` token.
  final Color borderSubtleSelected02;

  /// The `borderSubtle03` token.
  final Color borderSubtle03;

  /// The `borderSubtleSelected03` token.
  final Color borderSubtleSelected03;

  /// The `borderStrong01` token.
  final Color borderStrong01;

  /// The `borderStrong02` token.
  final Color borderStrong02;

  /// The `borderStrong03` token.
  final Color borderStrong03;

  /// The `borderTile01` token.
  final Color borderTile01;

  /// The `borderTile02` token.
  final Color borderTile02;

  /// The `borderTile03` token.
  final Color borderTile03;

  /// The `borderInverse` token.
  final Color borderInverse;

  /// The `borderInteractive` token.
  final Color borderInteractive;

  /// The `borderDisabled` token.
  final Color borderDisabled;

  /// The `textPrimary` token.
  final Color textPrimary;

  /// The `textSecondary` token.
  final Color textSecondary;

  /// The `textPlaceholder` token.
  final Color textPlaceholder;

  /// The `textHelper` token.
  final Color textHelper;

  /// The `textError` token.
  final Color textError;

  /// The `textInverse` token.
  final Color textInverse;

  /// The `textOnColor` token.
  final Color textOnColor;

  /// The `textOnColorDisabled` token.
  final Color textOnColorDisabled;

  /// The `textDisabled` token.
  final Color textDisabled;

  /// The `linkPrimary` token.
  final Color linkPrimary;

  /// The `linkPrimaryHover` token.
  final Color linkPrimaryHover;

  /// The `linkSecondary` token.
  final Color linkSecondary;

  /// The `linkInverse` token.
  final Color linkInverse;

  /// The `linkVisited` token.
  final Color linkVisited;

  /// The `linkInverseVisited` token.
  final Color linkInverseVisited;

  /// The `linkInverseActive` token.
  final Color linkInverseActive;

  /// The `linkInverseHover` token.
  final Color linkInverseHover;

  /// The `iconPrimary` token.
  final Color iconPrimary;

  /// The `iconSecondary` token.
  final Color iconSecondary;

  /// The `iconInverse` token.
  final Color iconInverse;

  /// The `iconOnColor` token.
  final Color iconOnColor;

  /// The `iconOnColorDisabled` token.
  final Color iconOnColorDisabled;

  /// The `iconDisabled` token.
  final Color iconDisabled;

  /// The `iconInteractive` token.
  final Color iconInteractive;

  /// The `supportError` token.
  final Color supportError;

  /// The `supportSuccess` token.
  final Color supportSuccess;

  /// The `supportWarning` token.
  final Color supportWarning;

  /// The `supportInfo` token.
  final Color supportInfo;

  /// The `supportErrorInverse` token.
  final Color supportErrorInverse;

  /// The `supportSuccessInverse` token.
  final Color supportSuccessInverse;

  /// The `supportWarningInverse` token.
  final Color supportWarningInverse;

  /// The `supportInfoInverse` token.
  final Color supportInfoInverse;

  /// The `supportCautionMinor` token.
  final Color supportCautionMinor;

  /// The `supportCautionMajor` token.
  final Color supportCautionMajor;

  /// The `supportCautionUndefined` token.
  final Color supportCautionUndefined;

  /// The `focus` token.
  final Color focus;

  /// The `focusInset` token.
  final Color focusInset;

  /// The `focusInverse` token.
  final Color focusInverse;

  /// The `skeletonBackground` token.
  final Color skeletonBackground;

  /// The `skeletonElement` token.
  final Color skeletonElement;

  /// The `interactive` token.
  final Color interactive;

  /// The `highlight` token.
  final Color highlight;

  /// The `overlay` token.
  final Color overlay;

  /// The `toggleOff` token.
  final Color toggleOff;

  /// The `shadow` token.
  final Color shadow;

  /// The White theme.
  static final CarbonThemeData white = CarbonThemeData(
    brightness: Brightness.light,
    background: CarbonColors.white,
    backgroundInverse: CarbonColors.gray80,
    backgroundBrand: CarbonColors.blue60,
    backgroundActive: _alpha(CarbonColors.gray50, 0.5),
    backgroundHover: _alpha(CarbonColors.gray50, 0.12),
    backgroundInverseHover: CarbonColors.gray80Hover,
    backgroundSelected: _alpha(CarbonColors.gray50, 0.2),
    backgroundSelectedHover: _alpha(CarbonColors.gray50, 0.32),
    layer01: CarbonColors.gray10,
    layerActive01: CarbonColors.gray30,
    layerBackground01: CarbonColors.white,
    layerHover01: CarbonColors.gray10Hover,
    layerSelected01: CarbonColors.gray20,
    layerSelectedHover01: CarbonColors.gray20Hover,
    layer02: CarbonColors.white,
    layerActive02: CarbonColors.gray30,
    layerBackground02: CarbonColors.gray10,
    layerHover02: CarbonColors.whiteHover,
    layerSelected02: CarbonColors.gray20,
    layerSelectedHover02: CarbonColors.gray20Hover,
    layer03: CarbonColors.gray10,
    layerActive03: CarbonColors.gray30,
    layerBackground03: CarbonColors.white,
    layerHover03: CarbonColors.gray10Hover,
    layerSelected03: CarbonColors.gray20,
    layerSelectedHover03: CarbonColors.gray20Hover,
    layerSelectedInverse: CarbonColors.gray100,
    layerSelectedDisabled: CarbonColors.gray50,
    layerAccent01: CarbonColors.gray20,
    layerAccentActive01: CarbonColors.gray40,
    layerAccentHover01: CarbonColors.gray20Hover,
    layerAccent02: CarbonColors.gray20,
    layerAccentActive02: CarbonColors.gray40,
    layerAccentHover02: CarbonColors.gray20Hover,
    layerAccent03: CarbonColors.gray20,
    layerAccentActive03: CarbonColors.gray40,
    layerAccentHover03: CarbonColors.gray20Hover,
    field01: CarbonColors.gray10,
    fieldHover01: CarbonColors.gray10Hover,
    field02: CarbonColors.white,
    fieldHover02: CarbonColors.whiteHover,
    field03: CarbonColors.gray10,
    fieldHover03: CarbonColors.gray10Hover,
    borderSubtle00: CarbonColors.gray20,
    borderSubtle01: CarbonColors.gray30,
    borderSubtleSelected01: CarbonColors.gray30,
    borderSubtle02: CarbonColors.gray20,
    borderSubtleSelected02: CarbonColors.gray30,
    borderSubtle03: CarbonColors.gray30,
    borderSubtleSelected03: CarbonColors.gray30,
    borderStrong01: CarbonColors.gray50,
    borderStrong02: CarbonColors.gray50,
    borderStrong03: CarbonColors.gray50,
    borderTile01: CarbonColors.gray30,
    borderTile02: CarbonColors.gray40,
    borderTile03: CarbonColors.gray30,
    borderInverse: CarbonColors.gray100,
    borderInteractive: CarbonColors.blue60,
    borderDisabled: CarbonColors.gray30,
    textPrimary: CarbonColors.gray100,
    textSecondary: CarbonColors.gray70,
    textPlaceholder: _alpha(CarbonColors.gray100, 0.4),
    textHelper: CarbonColors.gray60,
    textError: CarbonColors.red60,
    textInverse: CarbonColors.white,
    textOnColor: CarbonColors.white,
    textOnColorDisabled: CarbonColors.gray50,
    textDisabled: _alpha(CarbonColors.gray100, 0.25),
    linkPrimary: CarbonColors.blue60,
    linkPrimaryHover: CarbonColors.blue70,
    linkSecondary: CarbonColors.blue70,
    linkInverse: CarbonColors.blue40,
    linkVisited: CarbonColors.purple60,
    linkInverseVisited: CarbonColors.purple40,
    linkInverseActive: CarbonColors.gray10,
    linkInverseHover: CarbonColors.blue30,
    iconPrimary: CarbonColors.gray100,
    iconSecondary: CarbonColors.gray70,
    iconInverse: CarbonColors.white,
    iconOnColor: CarbonColors.white,
    iconOnColorDisabled: CarbonColors.gray50,
    iconDisabled: _alpha(CarbonColors.gray100, 0.25),
    iconInteractive: CarbonColors.blue60,
    supportError: CarbonColors.red60,
    supportSuccess: CarbonColors.green50,
    supportWarning: CarbonColors.yellow30,
    supportInfo: CarbonColors.blue70,
    supportErrorInverse: CarbonColors.red50,
    supportSuccessInverse: CarbonColors.green40,
    supportWarningInverse: CarbonColors.yellow30,
    supportInfoInverse: CarbonColors.blue50,
    supportCautionMinor: CarbonColors.yellow30,
    supportCautionMajor: CarbonColors.orange40,
    supportCautionUndefined: CarbonColors.purple60,
    focus: CarbonColors.blue60,
    focusInset: CarbonColors.white,
    focusInverse: CarbonColors.white,
    skeletonBackground: CarbonColors.whiteHover,
    skeletonElement: CarbonColors.gray30,
    interactive: CarbonColors.blue60,
    highlight: CarbonColors.blue20,
    overlay: _alpha(CarbonColors.black, 0.6),
    toggleOff: CarbonColors.gray50,
    shadow: const Color.fromRGBO(0, 0, 0, 0.3),
  );

  /// The Gray 10 theme.
  static final CarbonThemeData gray10 = CarbonThemeData(
    brightness: Brightness.light,
    background: CarbonColors.gray10,
    backgroundInverse: CarbonColors.gray80,
    backgroundBrand: CarbonColors.blue60,
    backgroundActive: _alpha(CarbonColors.gray50, 0.5),
    backgroundHover: _alpha(CarbonColors.gray50, 0.12),
    backgroundInverseHover: CarbonColors.gray80Hover,
    backgroundSelected: _alpha(CarbonColors.gray50, 0.2),
    backgroundSelectedHover: _alpha(CarbonColors.gray50, 0.32),
    layer01: CarbonColors.white,
    layerActive01: CarbonColors.gray30,
    layerBackground01: CarbonColors.gray10,
    layerHover01: CarbonColors.whiteHover,
    layerSelected01: CarbonColors.gray20,
    layerSelectedHover01: CarbonColors.gray20Hover,
    layer02: CarbonColors.gray10,
    layerActive02: CarbonColors.gray30,
    layerBackground02: CarbonColors.white,
    layerHover02: CarbonColors.gray10Hover,
    layerSelected02: CarbonColors.gray20,
    layerSelectedHover02: CarbonColors.gray20Hover,
    layer03: CarbonColors.white,
    layerActive03: CarbonColors.gray30,
    layerBackground03: CarbonColors.gray10,
    layerHover03: CarbonColors.whiteHover,
    layerSelected03: CarbonColors.gray20,
    layerSelectedHover03: CarbonColors.gray20Hover,
    layerSelectedInverse: CarbonColors.gray100,
    layerSelectedDisabled: CarbonColors.gray50,
    layerAccent01: CarbonColors.gray20,
    layerAccentActive01: CarbonColors.gray40,
    layerAccentHover01: CarbonColors.gray20Hover,
    layerAccent02: CarbonColors.gray20,
    layerAccentActive02: CarbonColors.gray40,
    layerAccentHover02: CarbonColors.gray20Hover,
    layerAccent03: CarbonColors.gray20,
    layerAccentActive03: CarbonColors.gray40,
    layerAccentHover03: CarbonColors.gray20Hover,
    field01: CarbonColors.white,
    fieldHover01: CarbonColors.whiteHover,
    field02: CarbonColors.gray10,
    fieldHover02: CarbonColors.gray10Hover,
    field03: CarbonColors.white,
    fieldHover03: CarbonColors.whiteHover,
    borderSubtle00: CarbonColors.gray30,
    borderSubtle01: CarbonColors.gray20,
    borderSubtleSelected01: CarbonColors.gray30,
    borderSubtle02: CarbonColors.gray30,
    borderSubtleSelected02: CarbonColors.gray30,
    borderSubtle03: CarbonColors.gray20,
    borderSubtleSelected03: CarbonColors.gray30,
    borderStrong01: CarbonColors.gray50,
    borderStrong02: CarbonColors.gray50,
    borderStrong03: CarbonColors.gray50,
    borderTile01: CarbonColors.gray40,
    borderTile02: CarbonColors.gray30,
    borderTile03: CarbonColors.gray40,
    borderInverse: CarbonColors.gray100,
    borderInteractive: CarbonColors.blue60,
    borderDisabled: CarbonColors.gray30,
    textPrimary: CarbonColors.gray100,
    textSecondary: CarbonColors.gray70,
    textPlaceholder: _alpha(CarbonColors.gray100, 0.4),
    textHelper: CarbonColors.gray60,
    textError: CarbonColors.red60,
    textInverse: CarbonColors.white,
    textOnColor: CarbonColors.white,
    textOnColorDisabled: CarbonColors.gray50,
    textDisabled: _alpha(CarbonColors.gray100, 0.25),
    linkPrimary: CarbonColors.blue60,
    linkPrimaryHover: CarbonColors.blue70,
    linkSecondary: CarbonColors.blue70,
    linkInverse: CarbonColors.blue40,
    linkVisited: CarbonColors.purple60,
    linkInverseVisited: CarbonColors.purple40,
    linkInverseActive: CarbonColors.gray10,
    linkInverseHover: CarbonColors.blue30,
    iconPrimary: CarbonColors.gray100,
    iconSecondary: CarbonColors.gray70,
    iconInverse: CarbonColors.white,
    iconOnColor: CarbonColors.white,
    iconOnColorDisabled: CarbonColors.gray50,
    iconDisabled: _alpha(CarbonColors.gray100, 0.25),
    iconInteractive: CarbonColors.blue60,
    supportError: CarbonColors.red60,
    supportSuccess: CarbonColors.green50,
    supportWarning: CarbonColors.yellow30,
    supportInfo: CarbonColors.blue70,
    supportErrorInverse: CarbonColors.red50,
    supportSuccessInverse: CarbonColors.green40,
    supportWarningInverse: CarbonColors.yellow30,
    supportInfoInverse: CarbonColors.blue50,
    supportCautionMinor: CarbonColors.yellow30,
    supportCautionMajor: CarbonColors.orange40,
    supportCautionUndefined: CarbonColors.purple60,
    focus: CarbonColors.blue60,
    focusInset: CarbonColors.white,
    focusInverse: CarbonColors.white,
    skeletonBackground: CarbonColors.gray10Hover,
    skeletonElement: CarbonColors.gray30,
    interactive: CarbonColors.blue60,
    highlight: CarbonColors.blue20,
    overlay: _alpha(CarbonColors.black, 0.6),
    toggleOff: CarbonColors.gray50,
    shadow: const Color.fromRGBO(0, 0, 0, 0.3),
  );

  /// The Gray 90 theme.
  static final CarbonThemeData gray90 = CarbonThemeData(
    brightness: Brightness.dark,
    background: CarbonColors.gray90,
    backgroundInverse: CarbonColors.gray10,
    backgroundBrand: CarbonColors.blue60,
    backgroundActive: _alpha(CarbonColors.gray50, 0.4),
    backgroundHover: _alpha(CarbonColors.gray50, 0.16),
    backgroundInverseHover: CarbonColors.gray10Hover,
    backgroundSelected: _alpha(CarbonColors.gray50, 0.24),
    backgroundSelectedHover: _alpha(CarbonColors.gray50, 0.32),
    layer01: CarbonColors.gray80,
    layerActive01: CarbonColors.gray60,
    layerBackground01: CarbonColors.gray90,
    layerHover01: CarbonColors.gray80Hover,
    layerSelected01: CarbonColors.gray70,
    layerSelectedHover01: CarbonColors.gray70Hover,
    layer02: CarbonColors.gray70,
    layerActive02: CarbonColors.gray50,
    layerBackground02: CarbonColors.gray80,
    layerHover02: CarbonColors.gray70Hover,
    layerSelected02: CarbonColors.gray60,
    layerSelectedHover02: CarbonColors.gray60Hover,
    layer03: CarbonColors.gray60,
    layerActive03: CarbonColors.gray80,
    layerBackground03: CarbonColors.gray70,
    layerHover03: CarbonColors.gray60Hover,
    layerSelected03: CarbonColors.gray70,
    layerSelectedHover03: CarbonColors.gray70Hover,
    layerSelectedInverse: CarbonColors.gray10,
    layerSelectedDisabled: CarbonColors.gray40,
    layerAccent01: CarbonColors.gray70,
    layerAccentActive01: CarbonColors.gray50,
    layerAccentHover01: CarbonColors.gray70Hover,
    layerAccent02: CarbonColors.gray60,
    layerAccentActive02: CarbonColors.gray80,
    layerAccentHover02: CarbonColors.gray60Hover,
    layerAccent03: CarbonColors.gray50,
    layerAccentActive03: CarbonColors.gray70,
    layerAccentHover03: CarbonColors.gray50Hover,
    field01: CarbonColors.gray80,
    fieldHover01: CarbonColors.gray80Hover,
    field02: CarbonColors.gray70,
    fieldHover02: CarbonColors.gray70Hover,
    field03: CarbonColors.gray60,
    fieldHover03: CarbonColors.gray60Hover,
    borderSubtle00: CarbonColors.gray70,
    borderSubtle01: CarbonColors.gray60,
    borderSubtleSelected01: CarbonColors.gray50,
    borderSubtle02: CarbonColors.gray50,
    borderSubtleSelected02: CarbonColors.gray40,
    borderSubtle03: CarbonColors.gray50,
    borderSubtleSelected03: CarbonColors.gray40,
    borderStrong01: CarbonColors.gray50,
    borderStrong02: CarbonColors.gray40,
    borderStrong03: CarbonColors.gray30,
    borderTile01: CarbonColors.gray60,
    borderTile02: CarbonColors.gray50,
    borderTile03: CarbonColors.gray40,
    borderInverse: CarbonColors.gray10,
    borderInteractive: CarbonColors.blue50,
    borderDisabled: _alpha(CarbonColors.gray50, 0.5),
    textPrimary: CarbonColors.gray10,
    textSecondary: CarbonColors.gray30,
    textPlaceholder: _alpha(CarbonColors.gray10, 0.4),
    textHelper: CarbonColors.gray30,
    textError: CarbonColors.red30,
    textInverse: CarbonColors.gray100,
    textOnColor: CarbonColors.white,
    textOnColorDisabled: _alpha(CarbonColors.white, 0.25),
    textDisabled: _alpha(CarbonColors.gray10, 0.25),
    linkPrimary: CarbonColors.blue40,
    linkPrimaryHover: CarbonColors.blue30,
    linkSecondary: CarbonColors.blue30,
    linkInverse: CarbonColors.blue60,
    linkVisited: CarbonColors.purple40,
    linkInverseVisited: CarbonColors.purple60,
    linkInverseActive: CarbonColors.gray100,
    linkInverseHover: CarbonColors.blue70,
    iconPrimary: CarbonColors.gray10,
    iconSecondary: CarbonColors.gray30,
    iconInverse: CarbonColors.gray100,
    iconOnColor: CarbonColors.white,
    iconOnColorDisabled: _alpha(CarbonColors.white, 0.25),
    iconDisabled: _alpha(CarbonColors.gray10, 0.25),
    iconInteractive: CarbonColors.white,
    supportError: CarbonColors.red40,
    supportSuccess: CarbonColors.green40,
    supportWarning: CarbonColors.yellow30,
    supportInfo: CarbonColors.blue50,
    supportErrorInverse: CarbonColors.red60,
    supportSuccessInverse: CarbonColors.green50,
    supportWarningInverse: CarbonColors.yellow30,
    supportInfoInverse: CarbonColors.blue70,
    supportCautionMinor: CarbonColors.yellow30,
    supportCautionMajor: CarbonColors.orange40,
    supportCautionUndefined: CarbonColors.purple50,
    focus: CarbonColors.white,
    focusInset: CarbonColors.gray100,
    focusInverse: CarbonColors.blue60,
    skeletonBackground: CarbonColors.gray90Hover,
    skeletonElement: CarbonColors.gray70,
    interactive: CarbonColors.blue50,
    highlight: CarbonColors.blue80,
    overlay: _alpha(CarbonColors.black, 0.6),
    toggleOff: CarbonColors.gray50,
    shadow: _alpha(CarbonColors.black, 0.8),
  );

  /// The Gray 100 theme.
  static final CarbonThemeData gray100 = CarbonThemeData(
    brightness: Brightness.dark,
    background: CarbonColors.gray100,
    backgroundInverse: CarbonColors.gray10,
    backgroundBrand: CarbonColors.blue60,
    backgroundActive: _alpha(CarbonColors.gray50, 0.4),
    backgroundHover: _alpha(CarbonColors.gray50, 0.16),
    backgroundInverseHover: CarbonColors.gray10Hover,
    backgroundSelected: _alpha(CarbonColors.gray50, 0.24),
    backgroundSelectedHover: _alpha(CarbonColors.gray50, 0.32),
    layer01: CarbonColors.gray90,
    layerActive01: CarbonColors.gray70,
    layerBackground01: CarbonColors.gray100,
    layerHover01: CarbonColors.gray90Hover,
    layerSelected01: CarbonColors.gray80,
    layerSelectedHover01: CarbonColors.gray80Hover,
    layer02: CarbonColors.gray80,
    layerActive02: CarbonColors.gray60,
    layerBackground02: CarbonColors.gray90,
    layerHover02: CarbonColors.gray80Hover,
    layerSelected02: CarbonColors.gray70,
    layerSelectedHover02: CarbonColors.gray70Hover,
    layer03: CarbonColors.gray70,
    layerActive03: CarbonColors.gray50,
    layerBackground03: CarbonColors.gray80,
    layerHover03: CarbonColors.gray70Hover,
    layerSelected03: CarbonColors.gray60,
    layerSelectedHover03: CarbonColors.gray60Hover,
    layerSelectedInverse: CarbonColors.gray10,
    layerSelectedDisabled: CarbonColors.gray40,
    layerAccent01: CarbonColors.gray80,
    layerAccentActive01: CarbonColors.gray60,
    layerAccentHover01: CarbonColors.gray80Hover,
    layerAccent02: CarbonColors.gray70,
    layerAccentActive02: CarbonColors.gray50,
    layerAccentHover02: CarbonColors.gray70Hover,
    layerAccent03: CarbonColors.gray60,
    layerAccentActive03: CarbonColors.gray80,
    layerAccentHover03: CarbonColors.gray60Hover,
    field01: CarbonColors.gray90,
    fieldHover01: CarbonColors.gray90Hover,
    field02: CarbonColors.gray80,
    fieldHover02: CarbonColors.gray80Hover,
    field03: CarbonColors.gray70,
    fieldHover03: CarbonColors.gray70Hover,
    borderSubtle00: CarbonColors.gray80,
    borderSubtle01: CarbonColors.gray70,
    borderSubtleSelected01: CarbonColors.gray60,
    borderSubtle02: CarbonColors.gray60,
    borderSubtleSelected02: CarbonColors.gray50,
    borderSubtle03: CarbonColors.gray60,
    borderSubtleSelected03: CarbonColors.gray50,
    borderStrong01: CarbonColors.gray60,
    borderStrong02: CarbonColors.gray50,
    borderStrong03: CarbonColors.gray40,
    borderTile01: CarbonColors.gray70,
    borderTile02: CarbonColors.gray60,
    borderTile03: CarbonColors.gray50,
    borderInverse: CarbonColors.gray10,
    borderInteractive: CarbonColors.blue50,
    borderDisabled: _alpha(CarbonColors.gray50, 0.5),
    textPrimary: CarbonColors.gray10,
    textSecondary: CarbonColors.gray30,
    textPlaceholder: _alpha(CarbonColors.gray10, 0.4),
    textHelper: CarbonColors.gray40,
    textError: CarbonColors.red40,
    textInverse: CarbonColors.gray100,
    textOnColor: CarbonColors.white,
    textOnColorDisabled: _alpha(CarbonColors.white, 0.25),
    textDisabled: _alpha(CarbonColors.gray10, 0.25),
    linkPrimary: CarbonColors.blue40,
    linkPrimaryHover: CarbonColors.blue30,
    linkSecondary: CarbonColors.blue30,
    linkInverse: CarbonColors.blue60,
    linkVisited: CarbonColors.purple40,
    linkInverseVisited: CarbonColors.purple60,
    linkInverseActive: CarbonColors.gray100,
    linkInverseHover: CarbonColors.blue70,
    iconPrimary: CarbonColors.gray10,
    iconSecondary: CarbonColors.gray30,
    iconInverse: CarbonColors.gray100,
    iconOnColor: CarbonColors.white,
    iconOnColorDisabled: _alpha(CarbonColors.white, 0.25),
    iconDisabled: _alpha(CarbonColors.gray10, 0.25),
    iconInteractive: CarbonColors.white,
    supportError: CarbonColors.red50,
    supportSuccess: CarbonColors.green40,
    supportWarning: CarbonColors.yellow30,
    supportInfo: CarbonColors.blue50,
    supportErrorInverse: CarbonColors.red60,
    supportSuccessInverse: CarbonColors.green50,
    supportWarningInverse: CarbonColors.yellow30,
    supportInfoInverse: CarbonColors.blue70,
    supportCautionMinor: CarbonColors.yellow30,
    supportCautionMajor: CarbonColors.orange40,
    supportCautionUndefined: CarbonColors.purple50,
    focus: CarbonColors.white,
    focusInset: CarbonColors.gray100,
    focusInverse: CarbonColors.blue60,
    skeletonBackground: const Color(0xFF292929),
    skeletonElement: CarbonColors.gray80,
    interactive: CarbonColors.blue50,
    highlight: CarbonColors.blue90,
    overlay: _alpha(CarbonColors.black, 0.6),
    toggleOff: CarbonColors.gray60,
    shadow: _alpha(CarbonColors.black, 0.8),
  );
}

Color _alpha(Color color, double opacity) => color.withValues(alpha: opacity);
